//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: meta_lifecycle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *ProtoFormat           `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetFormat() *ProtoFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *InitRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckVersion  bool                   `protobuf:"varint,1,opt,name=check_version,json=checkVersion,proto3" json:"check_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *LoadRequest) GetCheckVersion() bool {
	if x != nil {
		return x.CheckVersion
	}
	return false
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Format        *ProtoFormat           `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *LoadResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *LoadResponse) GetFormat() *ProtoFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

type NewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        bool                   `protobuf:"varint,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionRequest) Reset() {
	*x = NewSessionRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionRequest) ProtoMessage() {}

func (x *NewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionRequest.ProtoReflect.Descriptor instead.
func (*NewSessionRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *NewSessionRequest) GetRecord() bool {
	if x != nil {
		return x.Record
	}
	return false
}

type NewSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Sid           uint64                 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionResponse) Reset() {
	*x = NewSessionResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionResponse) ProtoMessage() {}

func (x *NewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionResponse.ProtoReflect.Descriptor instead.
func (*NewSessionResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *NewSessionResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *NewSessionResponse) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{6}
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSessionResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type FlushSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushSessionRequest) Reset() {
	*x = FlushSessionRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushSessionRequest) ProtoMessage() {}

func (x *FlushSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushSessionRequest.ProtoReflect.Descriptor instead.
func (*FlushSessionRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{8}
}

type FlushSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushSessionResponse) Reset() {
	*x = FlushSessionResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushSessionResponse) ProtoMessage() {}

func (x *FlushSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushSessionResponse.ProtoReflect.Descriptor instead.
func (*FlushSessionResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{9}
}

func (x *FlushSessionResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{10}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{11}
}

func (x *ShutdownResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{12}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{13}
}

func (x *ResetResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Detail        bool                   `protobuf:"varint,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{14}
}

func (x *GetSessionRequest) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *GetSessionRequest) GetDetail() bool {
	if x != nil {
		return x.Detail
	}
	return false
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Session       *ProtoSession          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{15}
}

func (x *GetSessionResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetSessionResponse) GetSession() *ProtoSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{16}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Sessions      []*ProtoSession        `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{17}
}

func (x *ListSessionsResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ListSessionsResponse) GetSessions() []*ProtoSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CleanStaleSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanStaleSessionsRequest) Reset() {
	*x = CleanStaleSessionsRequest{}
	mi := &file_meta_lifecycle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanStaleSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanStaleSessionsRequest) ProtoMessage() {}

func (x *CleanStaleSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanStaleSessionsRequest.ProtoReflect.Descriptor instead.
func (*CleanStaleSessionsRequest) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{18}
}

func (x *CleanStaleSessionsRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type CleanStaleSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanStaleSessionsResponse) Reset() {
	*x = CleanStaleSessionsResponse{}
	mi := &file_meta_lifecycle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanStaleSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanStaleSessionsResponse) ProtoMessage() {}

func (x *CleanStaleSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_lifecycle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanStaleSessionsResponse.ProtoReflect.Descriptor instead.
func (*CleanStaleSessionsResponse) Descriptor() ([]byte, []int) {
	return file_meta_lifecycle_proto_rawDescGZIP(), []int{19}
}

func (x *CleanStaleSessionsResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

var File_meta_lifecycle_proto protoreflect.FileDescriptor

const file_meta_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x14meta_lifecycle.proto\x12\x02pb\x1a\x11meta_common.proto\"L\n" +
	"\vInitRequest\x12'\n" +
	"\x06format\x18\x01 \x01(\v2\x0f.pb.ProtoFormatR\x06format\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"$\n" +
	"\fInitResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"2\n" +
	"\vLoadRequest\x12#\n" +
	"\rcheck_version\x18\x01 \x01(\bR\fcheckVersion\"M\n" +
	"\fLoadResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12'\n" +
	"\x06format\x18\x02 \x01(\v2\x0f.pb.ProtoFormatR\x06format\"+\n" +
	"\x11NewSessionRequest\x12\x16\n" +
	"\x06record\x18\x01 \x01(\bR\x06record\"<\n" +
	"\x12NewSessionResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x10\n" +
	"\x03sid\x18\x02 \x01(\x04R\x03sid\"\x15\n" +
	"\x13CloseSessionRequest\",\n" +
	"\x14CloseSessionResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"\x15\n" +
	"\x13FlushSessionRequest\",\n" +
	"\x14FlushSessionResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"\x11\n" +
	"\x0fShutdownRequest\"(\n" +
	"\x10ShutdownResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"\x0e\n" +
	"\fResetRequest\"%\n" +
	"\rResetResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"=\n" +
	"\x11GetSessionRequest\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\bR\x06detail\"V\n" +
	"\x12GetSessionResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12*\n" +
	"\asession\x18\x02 \x01(\v2\x10.pb.ProtoSessionR\asession\"\x15\n" +
	"\x13ListSessionsRequest\"Z\n" +
	"\x14ListSessionsResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12,\n" +
	"\bsessions\x18\x02 \x03(\v2\x10.pb.ProtoSessionR\bsessions\">\n" +
	"\x19CleanStaleSessionsRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\"2\n" +
	"\x1aCleanStaleSessionsResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errnoB\x06Z\x04./pbb\x06proto3"

var (
	file_meta_lifecycle_proto_rawDescOnce sync.Once
	file_meta_lifecycle_proto_rawDescData []byte
)

func file_meta_lifecycle_proto_rawDescGZIP() []byte {
	file_meta_lifecycle_proto_rawDescOnce.Do(func() {
		file_meta_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_lifecycle_proto_rawDesc), len(file_meta_lifecycle_proto_rawDesc)))
	})
	return file_meta_lifecycle_proto_rawDescData
}

var file_meta_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_meta_lifecycle_proto_goTypes = []any{
	(*InitRequest)(nil),                // 0: pb.InitRequest
	(*InitResponse)(nil),               // 1: pb.InitResponse
	(*LoadRequest)(nil),                // 2: pb.LoadRequest
	(*LoadResponse)(nil),               // 3: pb.LoadResponse
	(*NewSessionRequest)(nil),          // 4: pb.NewSessionRequest
	(*NewSessionResponse)(nil),         // 5: pb.NewSessionResponse
	(*CloseSessionRequest)(nil),        // 6: pb.CloseSessionRequest
	(*CloseSessionResponse)(nil),       // 7: pb.CloseSessionResponse
	(*FlushSessionRequest)(nil),        // 8: pb.FlushSessionRequest
	(*FlushSessionResponse)(nil),       // 9: pb.FlushSessionResponse
	(*ShutdownRequest)(nil),            // 10: pb.ShutdownRequest
	(*ShutdownResponse)(nil),           // 11: pb.ShutdownResponse
	(*ResetRequest)(nil),               // 12: pb.ResetRequest
	(*ResetResponse)(nil),              // 13: pb.ResetResponse
	(*GetSessionRequest)(nil),          // 14: pb.GetSessionRequest
	(*GetSessionResponse)(nil),         // 15: pb.GetSessionResponse
	(*ListSessionsRequest)(nil),        // 16: pb.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 17: pb.ListSessionsResponse
	(*CleanStaleSessionsRequest)(nil),  // 18: pb.CleanStaleSessionsRequest
	(*CleanStaleSessionsResponse)(nil), // 19: pb.CleanStaleSessionsResponse
	(*ProtoFormat)(nil),                // 20: pb.ProtoFormat
	(*ProtoSession)(nil),               // 21: pb.ProtoSession
	(*MetaContext)(nil),                // 22: pb.MetaContext
}
var file_meta_lifecycle_proto_depIdxs = []int32{
	20, // 0: pb.InitRequest.format:type_name -> pb.ProtoFormat
	20, // 1: pb.LoadResponse.format:type_name -> pb.ProtoFormat
	21, // 2: pb.GetSessionResponse.session:type_name -> pb.ProtoSession
	21, // 3: pb.ListSessionsResponse.sessions:type_name -> pb.ProtoSession
	22, // 4: pb.CleanStaleSessionsRequest.ctx:type_name -> pb.MetaContext
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_meta_lifecycle_proto_init() }
func file_meta_lifecycle_proto_init() {
	if File_meta_lifecycle_proto != nil {
		return
	}
	file_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_lifecycle_proto_rawDesc), len(file_meta_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_lifecycle_proto_goTypes,
		DependencyIndexes: file_meta_lifecycle_proto_depIdxs,
		MessageInfos:      file_meta_lifecycle_proto_msgTypes,
	}.Build()
	File_meta_lifecycle_proto = out.File
	file_meta_lifecycle_proto_goTypes = nil
	file_meta_lifecycle_proto_depIdxs = nil
}
