//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: pb/meta_admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormatRequest) Reset() {
	*x = GetFormatRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormatRequest) ProtoMessage() {}

func (x *GetFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormatRequest.ProtoReflect.Descriptor instead.
func (*GetFormatRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{0}
}

type GetFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Format        *ProtoFormat           `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormatResponse) Reset() {
	*x = GetFormatResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormatResponse) ProtoMessage() {}

func (x *GetFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormatResponse.ProtoReflect.Descriptor instead.
func (*GetFormatResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetFormatResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetFormatResponse) GetFormat() *ProtoFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Parent        uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SkipTrash     bool                   `protobuf:"varint,4,opt,name=skip_trash,json=skipTrash,proto3" json:"skip_trash,omitempty"`
	NumThreads    int32                  `protobuf:"varint,5,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *RemoveRequest) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *RemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveRequest) GetSkipTrash() bool {
	if x != nil {
		return x.SkipTrash
	}
	return false
}

func (x *RemoveRequest) GetNumThreads() int32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *RemoveResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BatchUnlinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ctx            *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Parent         uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Entries        []*ProtoEntry          `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	SkipCheckTrash bool                   `protobuf:"varint,4,opt,name=skip_check_trash,json=skipCheckTrash,proto3" json:"skip_check_trash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchUnlinkRequest) Reset() {
	*x = BatchUnlinkRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUnlinkRequest) ProtoMessage() {}

func (x *BatchUnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUnlinkRequest.ProtoReflect.Descriptor instead.
func (*BatchUnlinkRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUnlinkRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *BatchUnlinkRequest) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *BatchUnlinkRequest) GetEntries() []*ProtoEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *BatchUnlinkRequest) GetSkipCheckTrash() bool {
	if x != nil {
		return x.SkipCheckTrash
	}
	return false
}

type BatchUnlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUnlinkResponse) Reset() {
	*x = BatchUnlinkResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUnlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUnlinkResponse) ProtoMessage() {}

func (x *BatchUnlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUnlinkResponse.ProtoReflect.Descriptor instead.
func (*BatchUnlinkResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{5}
}

func (x *BatchUnlinkResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *BatchUnlinkResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Strict        bool                   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetSummaryRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetSummaryRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *GetSummaryRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *GetSummaryRequest) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Summary       *ProtoSummary          `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetSummaryResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetSummaryResponse) GetSummary() *ProtoSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type GetTreeSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Depth         uint32                 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	TopN          uint32                 `protobuf:"varint,4,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	Strict        bool                   `protobuf:"varint,5,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeSummaryRequest) Reset() {
	*x = GetTreeSummaryRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeSummaryRequest) ProtoMessage() {}

func (x *GetTreeSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetTreeSummaryRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetTreeSummaryRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetTreeSummaryRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *GetTreeSummaryRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GetTreeSummaryRequest) GetTopN() uint32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *GetTreeSummaryRequest) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type GetTreeSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Tree          *ProtoTreeSummary      `protobuf:"bytes,2,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeSummaryResponse) Reset() {
	*x = GetTreeSummaryResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeSummaryResponse) ProtoMessage() {}

func (x *GetTreeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetTreeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{9}
}

func (x *GetTreeSummaryResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetTreeSummaryResponse) GetTree() *ProtoTreeSummary {
	if x != nil {
		return x.Tree
	}
	return nil
}

type CloneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	SrcParentIno  uint64                 `protobuf:"varint,2,opt,name=src_parent_ino,json=srcParentIno,proto3" json:"src_parent_ino,omitempty"`
	SrcIno        uint64                 `protobuf:"varint,3,opt,name=src_ino,json=srcIno,proto3" json:"src_ino,omitempty"`
	DstParentIno  uint64                 `protobuf:"varint,4,opt,name=dst_parent_ino,json=dstParentIno,proto3" json:"dst_parent_ino,omitempty"`
	DstName       string                 `protobuf:"bytes,5,opt,name=dst_name,json=dstName,proto3" json:"dst_name,omitempty"`
	Cmode         uint32                 `protobuf:"varint,6,opt,name=cmode,proto3" json:"cmode,omitempty"`
	Cumask        uint32                 `protobuf:"varint,7,opt,name=cumask,proto3" json:"cumask,omitempty"`
	Concurrency   uint32                 `protobuf:"varint,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{10}
}

func (x *CloneRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CloneRequest) GetSrcParentIno() uint64 {
	if x != nil {
		return x.SrcParentIno
	}
	return 0
}

func (x *CloneRequest) GetSrcIno() uint64 {
	if x != nil {
		return x.SrcIno
	}
	return 0
}

func (x *CloneRequest) GetDstParentIno() uint64 {
	if x != nil {
		return x.DstParentIno
	}
	return 0
}

func (x *CloneRequest) GetDstName() string {
	if x != nil {
		return x.DstName
	}
	return ""
}

func (x *CloneRequest) GetCmode() uint32 {
	if x != nil {
		return x.Cmode
	}
	return 0
}

func (x *CloneRequest) GetCumask() uint32 {
	if x != nil {
		return x.Cumask
	}
	return 0
}

func (x *CloneRequest) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type CloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{11}
}

func (x *CloneResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *CloneResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CloneResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPathsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPathsRequest) Reset() {
	*x = GetPathsRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPathsRequest) ProtoMessage() {}

func (x *GetPathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPathsRequest.ProtoReflect.Descriptor instead.
func (*GetPathsRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetPathsRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetPathsRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type GetPathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPathsResponse) Reset() {
	*x = GetPathsResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPathsResponse) ProtoMessage() {}

func (x *GetPathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPathsResponse.ProtoReflect.Descriptor instead.
func (*GetPathsResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GetPathsResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetPathsResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Fpath         string                 `protobuf:"bytes,2,opt,name=fpath,proto3" json:"fpath,omitempty"`
	Repair        bool                   `protobuf:"varint,3,opt,name=repair,proto3" json:"repair,omitempty"`
	Recursive     bool                   `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	SyncDirStat   bool                   `protobuf:"varint,5,opt,name=sync_dir_stat,json=syncDirStat,proto3" json:"sync_dir_stat,omitempty"`
	RepairDirMode uint32                 `protobuf:"varint,6,opt,name=repair_dir_mode,json=repairDirMode,proto3" json:"repair_dir_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{14}
}

func (x *CheckRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CheckRequest) GetFpath() string {
	if x != nil {
		return x.Fpath
	}
	return ""
}

func (x *CheckRequest) GetRepair() bool {
	if x != nil {
		return x.Repair
	}
	return false
}

func (x *CheckRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CheckRequest) GetSyncDirStat() bool {
	if x != nil {
		return x.SyncDirStat
	}
	return false
}

func (x *CheckRequest) GetRepairDirMode() uint32 {
	if x != nil {
		return x.RepairDirMode
	}
	return 0
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{15}
}

func (x *CheckResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type CompactAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Threads       int32                  `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactAllRequest) Reset() {
	*x = CompactAllRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactAllRequest) ProtoMessage() {}

func (x *CompactAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactAllRequest.ProtoReflect.Descriptor instead.
func (*CompactAllRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CompactAllRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CompactAllRequest) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type CompactAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactAllResponse) Reset() {
	*x = CompactAllResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactAllResponse) ProtoMessage() {}

func (x *CompactAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactAllResponse.ProtoReflect.Descriptor instead.
func (*CompactAllResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{17}
}

func (x *CompactAllResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Concurrency   int32                  `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{18}
}

func (x *CompactRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CompactRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *CompactRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{19}
}

func (x *CompactResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ListSlicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Slices        []*SliceMapEntry       `protobuf:"bytes,2,rep,name=slices,proto3" json:"slices,omitempty"`
	ScanPending   bool                   `protobuf:"varint,3,opt,name=scan_pending,json=scanPending,proto3" json:"scan_pending,omitempty"`
	Delete        bool                   `protobuf:"varint,4,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesRequest) Reset() {
	*x = ListSlicesRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesRequest) ProtoMessage() {}

func (x *ListSlicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesRequest.ProtoReflect.Descriptor instead.
func (*ListSlicesRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListSlicesRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ListSlicesRequest) GetSlices() []*SliceMapEntry {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *ListSlicesRequest) GetScanPending() bool {
	if x != nil {
		return x.ScanPending
	}
	return false
}

func (x *ListSlicesRequest) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type ListSlicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Slices        []*SliceMapEntry       `protobuf:"bytes,2,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesResponse) Reset() {
	*x = ListSlicesResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesResponse) ProtoMessage() {}

func (x *ListSlicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesResponse.ProtoReflect.Descriptor instead.
func (*ListSlicesResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListSlicesResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ListSlicesResponse) GetSlices() []*SliceMapEntry {
	if x != nil {
		return x.Slices
	}
	return nil
}

type HandleQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Cmd           uint32                 `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Dpath         string                 `protobuf:"bytes,3,opt,name=dpath,proto3" json:"dpath,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Quotas        map[string]*ProtoQuota `protobuf:"bytes,6,rep,name=quotas,proto3" json:"quotas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Strict        bool                   `protobuf:"varint,7,opt,name=strict,proto3" json:"strict,omitempty"`
	Repair        bool                   `protobuf:"varint,8,opt,name=repair,proto3" json:"repair,omitempty"`
	Create        bool                   `protobuf:"varint,9,opt,name=create,proto3" json:"create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleQuotaRequest) Reset() {
	*x = HandleQuotaRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleQuotaRequest) ProtoMessage() {}

func (x *HandleQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleQuotaRequest.ProtoReflect.Descriptor instead.
func (*HandleQuotaRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{22}
}

func (x *HandleQuotaRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *HandleQuotaRequest) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *HandleQuotaRequest) GetDpath() string {
	if x != nil {
		return x.Dpath
	}
	return ""
}

func (x *HandleQuotaRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *HandleQuotaRequest) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *HandleQuotaRequest) GetQuotas() map[string]*ProtoQuota {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *HandleQuotaRequest) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *HandleQuotaRequest) GetRepair() bool {
	if x != nil {
		return x.Repair
	}
	return false
}

func (x *HandleQuotaRequest) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

type HandleQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleQuotaResponse) Reset() {
	*x = HandleQuotaResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleQuotaResponse) ProtoMessage() {}

func (x *HandleQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleQuotaResponse.ProtoReflect.Descriptor instead.
func (*HandleQuotaResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{23}
}

func (x *HandleQuotaResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ScanUserGroupUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanUserGroupUsageRequest) Reset() {
	*x = ScanUserGroupUsageRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanUserGroupUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanUserGroupUsageRequest) ProtoMessage() {}

func (x *ScanUserGroupUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanUserGroupUsageRequest.ProtoReflect.Descriptor instead.
func (*ScanUserGroupUsageRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ScanUserGroupUsageRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type ScanUserGroupUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanUserGroupUsageResponse) Reset() {
	*x = ScanUserGroupUsageResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanUserGroupUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanUserGroupUsageResponse) ProtoMessage() {}

func (x *ScanUserGroupUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanUserGroupUsageResponse.ProtoReflect.Descriptor instead.
func (*ScanUserGroupUsageResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ScanUserGroupUsageResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ChrootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Subdir        string                 `protobuf:"bytes,2,opt,name=subdir,proto3" json:"subdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChrootRequest) Reset() {
	*x = ChrootRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChrootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrootRequest) ProtoMessage() {}

func (x *ChrootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrootRequest.ProtoReflect.Descriptor instead.
func (*ChrootRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{26}
}

func (x *ChrootRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ChrootRequest) GetSubdir() string {
	if x != nil {
		return x.Subdir
	}
	return ""
}

type ChrootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChrootResponse) Reset() {
	*x = ChrootResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChrootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrootResponse) ProtoMessage() {}

func (x *ChrootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrootResponse.ProtoReflect.Descriptor instead.
func (*ChrootResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{27}
}

func (x *ChrootResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type CleanupTrashBeforeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Edge          int64                  `protobuf:"varint,2,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupTrashBeforeRequest) Reset() {
	*x = CleanupTrashBeforeRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupTrashBeforeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupTrashBeforeRequest) ProtoMessage() {}

func (x *CleanupTrashBeforeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupTrashBeforeRequest.ProtoReflect.Descriptor instead.
func (*CleanupTrashBeforeRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{28}
}

func (x *CleanupTrashBeforeRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CleanupTrashBeforeRequest) GetEdge() int64 {
	if x != nil {
		return x.Edge
	}
	return 0
}

type CleanupTrashBeforeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	DeletedFiles  int64                  `protobuf:"varint,2,opt,name=deleted_files,json=deletedFiles,proto3" json:"deleted_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupTrashBeforeResponse) Reset() {
	*x = CleanupTrashBeforeResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupTrashBeforeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupTrashBeforeResponse) ProtoMessage() {}

func (x *CleanupTrashBeforeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupTrashBeforeResponse.ProtoReflect.Descriptor instead.
func (*CleanupTrashBeforeResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{29}
}

func (x *CleanupTrashBeforeResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *CleanupTrashBeforeResponse) GetDeletedFiles() int64 {
	if x != nil {
		return x.DeletedFiles
	}
	return 0
}

type CleanupDetachedNodesBeforeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Edge          int64                  `protobuf:"varint,2,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupDetachedNodesBeforeRequest) Reset() {
	*x = CleanupDetachedNodesBeforeRequest{}
	mi := &file_pb_meta_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupDetachedNodesBeforeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupDetachedNodesBeforeRequest) ProtoMessage() {}

func (x *CleanupDetachedNodesBeforeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupDetachedNodesBeforeRequest.ProtoReflect.Descriptor instead.
func (*CleanupDetachedNodesBeforeRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{30}
}

func (x *CleanupDetachedNodesBeforeRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CleanupDetachedNodesBeforeRequest) GetEdge() int64 {
	if x != nil {
		return x.Edge
	}
	return 0
}

type CleanupDetachedNodesBeforeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupDetachedNodesBeforeResponse) Reset() {
	*x = CleanupDetachedNodesBeforeResponse{}
	mi := &file_pb_meta_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupDetachedNodesBeforeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupDetachedNodesBeforeResponse) ProtoMessage() {}

func (x *CleanupDetachedNodesBeforeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupDetachedNodesBeforeResponse.ProtoReflect.Descriptor instead.
func (*CleanupDetachedNodesBeforeResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_admin_proto_rawDescGZIP(), []int{31}
}

func (x *CleanupDetachedNodesBeforeResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

var File_pb_meta_admin_proto protoreflect.FileDescriptor

const file_pb_meta_admin_proto_rawDesc = "" +
	"\n" +
	"\x13pb/meta_admin.proto\x12\x02pb\x1a\x14pb/meta_common.proto\"\x12\n" +
	"\x10GetFormatRequest\"R\n" +
	"\x11GetFormatResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12'\n" +
	"\x06format\x18\x02 \x01(\v2\x0f.pb.ProtoFormatR\x06format\"\x9e\x01\n" +
	"\rRemoveRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"skip_trash\x18\x04 \x01(\bR\tskipTrash\x12\x1f\n" +
	"\vnum_threads\x18\x05 \x01(\x05R\n" +
	"numThreads\"<\n" +
	"\x0eRemoveResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xa3\x01\n" +
	"\x12BatchUnlinkRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12(\n" +
	"\aentries\x18\x03 \x03(\v2\x0e.pb.ProtoEntryR\aentries\x12(\n" +
	"\x10skip_check_trash\x18\x04 \x01(\bR\x0eskipCheckTrash\"A\n" +
	"\x13BatchUnlinkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\x82\x01\n" +
	"\x11GetSummaryRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\"V\n" +
	"\x12GetSummaryResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12*\n" +
	"\asummary\x18\x02 \x01(\v2\x10.pb.ProtoSummaryR\asummary\"\x93\x01\n" +
	"\x15GetTreeSummaryRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\x12\x13\n" +
	"\x05top_n\x18\x04 \x01(\rR\x04topN\x12\x16\n" +
	"\x06strict\x18\x05 \x01(\bR\x06strict\"X\n" +
	"\x16GetTreeSummaryResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12(\n" +
	"\x04tree\x18\x02 \x01(\v2\x14.pb.ProtoTreeSummaryR\x04tree\"\x81\x02\n" +
	"\fCloneRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12$\n" +
	"\x0esrc_parent_ino\x18\x02 \x01(\x04R\fsrcParentIno\x12\x17\n" +
	"\asrc_ino\x18\x03 \x01(\x04R\x06srcIno\x12$\n" +
	"\x0edst_parent_ino\x18\x04 \x01(\x04R\fdstParentIno\x12\x19\n" +
	"\bdst_name\x18\x05 \x01(\tR\adstName\x12\x14\n" +
	"\x05cmode\x18\x06 \x01(\rR\x05cmode\x12\x16\n" +
	"\x06cumask\x18\a \x01(\rR\x06cumask\x12 \n" +
	"\vconcurrency\x18\b \x01(\rR\vconcurrency\"Q\n" +
	"\rCloneResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"J\n" +
	"\x0fGetPathsRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\">\n" +
	"\x10GetPathsResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"\xc9\x01\n" +
	"\fCheckRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05fpath\x18\x02 \x01(\tR\x05fpath\x12\x16\n" +
	"\x06repair\x18\x03 \x01(\bR\x06repair\x12\x1c\n" +
	"\trecursive\x18\x04 \x01(\bR\trecursive\x12\"\n" +
	"\rsync_dir_stat\x18\x05 \x01(\bR\vsyncDirStat\x12&\n" +
	"\x0frepair_dir_mode\x18\x06 \x01(\rR\rrepairDirMode\"%\n" +
	"\rCheckResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"P\n" +
	"\x11CompactAllRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x18\n" +
	"\athreads\x18\x02 \x01(\x05R\athreads\"*\n" +
	"\x12CompactAllResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"k\n" +
	"\x0eCompactRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\x05R\vconcurrency\"'\n" +
	"\x0fCompactResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"\x9c\x01\n" +
	"\x11ListSlicesRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12)\n" +
	"\x06slices\x18\x02 \x03(\v2\x11.pb.SliceMapEntryR\x06slices\x12!\n" +
	"\fscan_pending\x18\x03 \x01(\bR\vscanPending\x12\x16\n" +
	"\x06delete\x18\x04 \x01(\bR\x06delete\"U\n" +
	"\x12ListSlicesResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12)\n" +
	"\x06slices\x18\x02 \x03(\v2\x11.pb.SliceMapEntryR\x06slices\"\xd2\x02\n" +
	"\x12HandleQuotaRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\rR\x03cmd\x12\x14\n" +
	"\x05dpath\x18\x03 \x01(\tR\x05dpath\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12:\n" +
	"\x06quotas\x18\x06 \x03(\v2\".pb.HandleQuotaRequest.QuotasEntryR\x06quotas\x12\x16\n" +
	"\x06strict\x18\a \x01(\bR\x06strict\x12\x16\n" +
	"\x06repair\x18\b \x01(\bR\x06repair\x12\x16\n" +
	"\x06create\x18\t \x01(\bR\x06create\x1aI\n" +
	"\vQuotasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.pb.ProtoQuotaR\x05value:\x028\x01\"+\n" +
	"\x13HandleQuotaResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\">\n" +
	"\x19ScanUserGroupUsageRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\"2\n" +
	"\x1aScanUserGroupUsageResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"J\n" +
	"\rChrootRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x16\n" +
	"\x06subdir\x18\x02 \x01(\tR\x06subdir\"&\n" +
	"\x0eChrootResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"R\n" +
	"\x19CleanupTrashBeforeRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x12\n" +
	"\x04edge\x18\x02 \x01(\x03R\x04edge\"W\n" +
	"\x1aCleanupTrashBeforeResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12#\n" +
	"\rdeleted_files\x18\x02 \x01(\x03R\fdeletedFiles\"Z\n" +
	"!CleanupDetachedNodesBeforeRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x12\n" +
	"\x04edge\x18\x02 \x01(\x03R\x04edge\":\n" +
	"\"CleanupDetachedNodesBeforeResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errnoB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_meta_admin_proto_rawDescOnce sync.Once
	file_pb_meta_admin_proto_rawDescData []byte
)

func file_pb_meta_admin_proto_rawDescGZIP() []byte {
	file_pb_meta_admin_proto_rawDescOnce.Do(func() {
		file_pb_meta_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_meta_admin_proto_rawDesc), len(file_pb_meta_admin_proto_rawDesc)))
	})
	return file_pb_meta_admin_proto_rawDescData
}

var file_pb_meta_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_pb_meta_admin_proto_goTypes = []any{
	(*GetFormatRequest)(nil),                   // 0: pb.GetFormatRequest
	(*GetFormatResponse)(nil),                  // 1: pb.GetFormatResponse
	(*RemoveRequest)(nil),                      // 2: pb.RemoveRequest
	(*RemoveResponse)(nil),                     // 3: pb.RemoveResponse
	(*BatchUnlinkRequest)(nil),                 // 4: pb.BatchUnlinkRequest
	(*BatchUnlinkResponse)(nil),                // 5: pb.BatchUnlinkResponse
	(*GetSummaryRequest)(nil),                  // 6: pb.GetSummaryRequest
	(*GetSummaryResponse)(nil),                 // 7: pb.GetSummaryResponse
	(*GetTreeSummaryRequest)(nil),              // 8: pb.GetTreeSummaryRequest
	(*GetTreeSummaryResponse)(nil),             // 9: pb.GetTreeSummaryResponse
	(*CloneRequest)(nil),                       // 10: pb.CloneRequest
	(*CloneResponse)(nil),                      // 11: pb.CloneResponse
	(*GetPathsRequest)(nil),                    // 12: pb.GetPathsRequest
	(*GetPathsResponse)(nil),                   // 13: pb.GetPathsResponse
	(*CheckRequest)(nil),                       // 14: pb.CheckRequest
	(*CheckResponse)(nil),                      // 15: pb.CheckResponse
	(*CompactAllRequest)(nil),                  // 16: pb.CompactAllRequest
	(*CompactAllResponse)(nil),                 // 17: pb.CompactAllResponse
	(*CompactRequest)(nil),                     // 18: pb.CompactRequest
	(*CompactResponse)(nil),                    // 19: pb.CompactResponse
	(*ListSlicesRequest)(nil),                  // 20: pb.ListSlicesRequest
	(*ListSlicesResponse)(nil),                 // 21: pb.ListSlicesResponse
	(*HandleQuotaRequest)(nil),                 // 22: pb.HandleQuotaRequest
	(*HandleQuotaResponse)(nil),                // 23: pb.HandleQuotaResponse
	(*ScanUserGroupUsageRequest)(nil),          // 24: pb.ScanUserGroupUsageRequest
	(*ScanUserGroupUsageResponse)(nil),         // 25: pb.ScanUserGroupUsageResponse
	(*ChrootRequest)(nil),                      // 26: pb.ChrootRequest
	(*ChrootResponse)(nil),                     // 27: pb.ChrootResponse
	(*CleanupTrashBeforeRequest)(nil),          // 28: pb.CleanupTrashBeforeRequest
	(*CleanupTrashBeforeResponse)(nil),         // 29: pb.CleanupTrashBeforeResponse
	(*CleanupDetachedNodesBeforeRequest)(nil),  // 30: pb.CleanupDetachedNodesBeforeRequest
	(*CleanupDetachedNodesBeforeResponse)(nil), // 31: pb.CleanupDetachedNodesBeforeResponse
	nil,                      // 32: pb.HandleQuotaRequest.QuotasEntry
	(*ProtoFormat)(nil),      // 33: pb.ProtoFormat
	(*MetaContext)(nil),      // 34: pb.MetaContext
	(*ProtoEntry)(nil),       // 35: pb.ProtoEntry
	(*ProtoSummary)(nil),     // 36: pb.ProtoSummary
	(*ProtoTreeSummary)(nil), // 37: pb.ProtoTreeSummary
	(*SliceMapEntry)(nil),    // 38: pb.SliceMapEntry
	(*ProtoQuota)(nil),       // 39: pb.ProtoQuota
}
var file_pb_meta_admin_proto_depIdxs = []int32{
	33, // 0: pb.GetFormatResponse.format:type_name -> pb.ProtoFormat
	34, // 1: pb.RemoveRequest.ctx:type_name -> pb.MetaContext
	34, // 2: pb.BatchUnlinkRequest.ctx:type_name -> pb.MetaContext
	35, // 3: pb.BatchUnlinkRequest.entries:type_name -> pb.ProtoEntry
	34, // 4: pb.GetSummaryRequest.ctx:type_name -> pb.MetaContext
	36, // 5: pb.GetSummaryResponse.summary:type_name -> pb.ProtoSummary
	34, // 6: pb.GetTreeSummaryRequest.ctx:type_name -> pb.MetaContext
	37, // 7: pb.GetTreeSummaryResponse.tree:type_name -> pb.ProtoTreeSummary
	34, // 8: pb.CloneRequest.ctx:type_name -> pb.MetaContext
	34, // 9: pb.GetPathsRequest.ctx:type_name -> pb.MetaContext
	34, // 10: pb.CheckRequest.ctx:type_name -> pb.MetaContext
	34, // 11: pb.CompactAllRequest.ctx:type_name -> pb.MetaContext
	34, // 12: pb.CompactRequest.ctx:type_name -> pb.MetaContext
	34, // 13: pb.ListSlicesRequest.ctx:type_name -> pb.MetaContext
	38, // 14: pb.ListSlicesRequest.slices:type_name -> pb.SliceMapEntry
	38, // 15: pb.ListSlicesResponse.slices:type_name -> pb.SliceMapEntry
	34, // 16: pb.HandleQuotaRequest.ctx:type_name -> pb.MetaContext
	32, // 17: pb.HandleQuotaRequest.quotas:type_name -> pb.HandleQuotaRequest.QuotasEntry
	34, // 18: pb.ScanUserGroupUsageRequest.ctx:type_name -> pb.MetaContext
	34, // 19: pb.ChrootRequest.ctx:type_name -> pb.MetaContext
	34, // 20: pb.CleanupTrashBeforeRequest.ctx:type_name -> pb.MetaContext
	34, // 21: pb.CleanupDetachedNodesBeforeRequest.ctx:type_name -> pb.MetaContext
	39, // 22: pb.HandleQuotaRequest.QuotasEntry.value:type_name -> pb.ProtoQuota
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pb_meta_admin_proto_init() }
func file_pb_meta_admin_proto_init() {
	if File_pb_meta_admin_proto != nil {
		return
	}
	file_pb_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_meta_admin_proto_rawDesc), len(file_pb_meta_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_meta_admin_proto_goTypes,
		DependencyIndexes: file_pb_meta_admin_proto_depIdxs,
		MessageInfos:      file_pb_meta_admin_proto_msgTypes,
	}.Build()
	File_pb_meta_admin_proto = out.File
	file_pb_meta_admin_proto_goTypes = nil
	file_pb_meta_admin_proto_depIdxs = nil
}
