//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: pb/meta_xattrs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetXattrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXattrRequest) Reset() {
	*x = GetXattrRequest{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXattrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXattrRequest) ProtoMessage() {}

func (x *GetXattrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXattrRequest.ProtoReflect.Descriptor instead.
func (*GetXattrRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{0}
}

func (x *GetXattrRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetXattrRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *GetXattrRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetXattrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXattrResponse) Reset() {
	*x = GetXattrResponse{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXattrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXattrResponse) ProtoMessage() {}

func (x *GetXattrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXattrResponse.ProtoReflect.Descriptor instead.
func (*GetXattrResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{1}
}

func (x *GetXattrResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetXattrResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetXattrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetXattrRequest) Reset() {
	*x = SetXattrRequest{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetXattrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetXattrRequest) ProtoMessage() {}

func (x *SetXattrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetXattrRequest.ProtoReflect.Descriptor instead.
func (*SetXattrRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{2}
}

func (x *SetXattrRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *SetXattrRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *SetXattrRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetXattrRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetXattrRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type SetXattrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetXattrResponse) Reset() {
	*x = SetXattrResponse{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetXattrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetXattrResponse) ProtoMessage() {}

func (x *SetXattrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetXattrResponse.ProtoReflect.Descriptor instead.
func (*SetXattrResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{3}
}

func (x *SetXattrResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type RemoveXattrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveXattrRequest) Reset() {
	*x = RemoveXattrRequest{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveXattrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveXattrRequest) ProtoMessage() {}

func (x *RemoveXattrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveXattrRequest.ProtoReflect.Descriptor instead.
func (*RemoveXattrRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveXattrRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *RemoveXattrRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *RemoveXattrRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveXattrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveXattrResponse) Reset() {
	*x = RemoveXattrResponse{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveXattrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveXattrResponse) ProtoMessage() {}

func (x *RemoveXattrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveXattrResponse.ProtoReflect.Descriptor instead.
func (*RemoveXattrResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveXattrResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ListXattrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListXattrRequest) Reset() {
	*x = ListXattrRequest{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListXattrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListXattrRequest) ProtoMessage() {}

func (x *ListXattrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListXattrRequest.ProtoReflect.Descriptor instead.
func (*ListXattrRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{6}
}

func (x *ListXattrRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ListXattrRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type ListXattrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Names         []byte                 `protobuf:"bytes,2,opt,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListXattrResponse) Reset() {
	*x = ListXattrResponse{}
	mi := &file_pb_meta_xattrs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListXattrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListXattrResponse) ProtoMessage() {}

func (x *ListXattrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_xattrs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListXattrResponse.ProtoReflect.Descriptor instead.
func (*ListXattrResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_xattrs_proto_rawDescGZIP(), []int{7}
}

func (x *ListXattrResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ListXattrResponse) GetNames() []byte {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_pb_meta_xattrs_proto protoreflect.FileDescriptor

const file_pb_meta_xattrs_proto_rawDesc = "" +
	"\n" +
	"\x14pb/meta_xattrs.proto\x12\x02pb\x1a\x14pb/meta_common.proto\"^\n" +
	"\x0fGetXattrRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\">\n" +
	"\x10GetXattrResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x8a\x01\n" +
	"\x0fSetXattrRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\"(\n" +
	"\x10SetXattrResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"a\n" +
	"\x12RemoveXattrRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"+\n" +
	"\x13RemoveXattrResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"K\n" +
	"\x10ListXattrRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\"?\n" +
	"\x11ListXattrResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05names\x18\x02 \x01(\fR\x05namesB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_meta_xattrs_proto_rawDescOnce sync.Once
	file_pb_meta_xattrs_proto_rawDescData []byte
)

func file_pb_meta_xattrs_proto_rawDescGZIP() []byte {
	file_pb_meta_xattrs_proto_rawDescOnce.Do(func() {
		file_pb_meta_xattrs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_meta_xattrs_proto_rawDesc), len(file_pb_meta_xattrs_proto_rawDesc)))
	})
	return file_pb_meta_xattrs_proto_rawDescData
}

var file_pb_meta_xattrs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_meta_xattrs_proto_goTypes = []any{
	(*GetXattrRequest)(nil),     // 0: pb.GetXattrRequest
	(*GetXattrResponse)(nil),    // 1: pb.GetXattrResponse
	(*SetXattrRequest)(nil),     // 2: pb.SetXattrRequest
	(*SetXattrResponse)(nil),    // 3: pb.SetXattrResponse
	(*RemoveXattrRequest)(nil),  // 4: pb.RemoveXattrRequest
	(*RemoveXattrResponse)(nil), // 5: pb.RemoveXattrResponse
	(*ListXattrRequest)(nil),    // 6: pb.ListXattrRequest
	(*ListXattrResponse)(nil),   // 7: pb.ListXattrResponse
	(*MetaContext)(nil),         // 8: pb.MetaContext
}
var file_pb_meta_xattrs_proto_depIdxs = []int32{
	8, // 0: pb.GetXattrRequest.ctx:type_name -> pb.MetaContext
	8, // 1: pb.SetXattrRequest.ctx:type_name -> pb.MetaContext
	8, // 2: pb.RemoveXattrRequest.ctx:type_name -> pb.MetaContext
	8, // 3: pb.ListXattrRequest.ctx:type_name -> pb.MetaContext
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_meta_xattrs_proto_init() }
func file_pb_meta_xattrs_proto_init() {
	if File_pb_meta_xattrs_proto != nil {
		return
	}
	file_pb_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_meta_xattrs_proto_rawDesc), len(file_pb_meta_xattrs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_meta_xattrs_proto_goTypes,
		DependencyIndexes: file_pb_meta_xattrs_proto_depIdxs,
		MessageInfos:      file_pb_meta_xattrs_proto_msgTypes,
	}.Build()
	File_pb_meta_xattrs_proto = out.File
	file_pb_meta_xattrs_proto_goTypes = nil
	file_pb_meta_xattrs_proto_depIdxs = nil
}
