//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: meta_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetaContext carries uid/gid/pid for permission checks
type MetaContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid             uint32                 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	Gids            []uint32               `protobuf:"varint,3,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	Pid             uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	CheckPermission bool                   `protobuf:"varint,5,opt,name=check_permission,json=checkPermission,proto3" json:"check_permission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetaContext) Reset() {
	*x = MetaContext{}
	mi := &file_meta_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaContext) ProtoMessage() {}

func (x *MetaContext) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaContext.ProtoReflect.Descriptor instead.
func (*MetaContext) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{0}
}

func (x *MetaContext) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MetaContext) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *MetaContext) GetGids() []uint32 {
	if x != nil {
		return x.Gids
	}
	return nil
}

func (x *MetaContext) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MetaContext) GetCheckPermission() bool {
	if x != nil {
		return x.CheckPermission
	}
	return false
}

// Attr represents file/directory attributes
type ProtoAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Typ           uint32                 `protobuf:"varint,2,opt,name=typ,proto3" json:"typ,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Rdev          uint32                 `protobuf:"varint,6,opt,name=rdev,proto3" json:"rdev,omitempty"`
	Atime         int64                  `protobuf:"varint,7,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime         int64                  `protobuf:"varint,8,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime         int64                  `protobuf:"varint,9,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Atimensec     uint32                 `protobuf:"varint,10,opt,name=atimensec,proto3" json:"atimensec,omitempty"`
	Mtimensec     uint32                 `protobuf:"varint,11,opt,name=mtimensec,proto3" json:"mtimensec,omitempty"`
	Ctimensec     uint32                 `protobuf:"varint,12,opt,name=ctimensec,proto3" json:"ctimensec,omitempty"`
	Nlink         uint32                 `protobuf:"varint,13,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Length        uint64                 `protobuf:"varint,14,opt,name=length,proto3" json:"length,omitempty"`
	Parent        uint64                 `protobuf:"varint,15,opt,name=parent,proto3" json:"parent,omitempty"`
	Full          bool                   `protobuf:"varint,16,opt,name=full,proto3" json:"full,omitempty"`
	KeepCache     bool                   `protobuf:"varint,17,opt,name=keep_cache,json=keepCache,proto3" json:"keep_cache,omitempty"`
	AccessAcl     uint32                 `protobuf:"varint,18,opt,name=access_acl,json=accessAcl,proto3" json:"access_acl,omitempty"`
	DefaultAcl    uint32                 `protobuf:"varint,19,opt,name=default_acl,json=defaultAcl,proto3" json:"default_acl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoAttr) Reset() {
	*x = ProtoAttr{}
	mi := &file_meta_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoAttr) ProtoMessage() {}

func (x *ProtoAttr) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoAttr.ProtoReflect.Descriptor instead.
func (*ProtoAttr) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoAttr) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *ProtoAttr) GetTyp() uint32 {
	if x != nil {
		return x.Typ
	}
	return 0
}

func (x *ProtoAttr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ProtoAttr) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProtoAttr) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProtoAttr) GetRdev() uint32 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *ProtoAttr) GetAtime() int64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

func (x *ProtoAttr) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *ProtoAttr) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *ProtoAttr) GetAtimensec() uint32 {
	if x != nil {
		return x.Atimensec
	}
	return 0
}

func (x *ProtoAttr) GetMtimensec() uint32 {
	if x != nil {
		return x.Mtimensec
	}
	return 0
}

func (x *ProtoAttr) GetCtimensec() uint32 {
	if x != nil {
		return x.Ctimensec
	}
	return 0
}

func (x *ProtoAttr) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *ProtoAttr) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ProtoAttr) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *ProtoAttr) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *ProtoAttr) GetKeepCache() bool {
	if x != nil {
		return x.KeepCache
	}
	return false
}

func (x *ProtoAttr) GetAccessAcl() uint32 {
	if x != nil {
		return x.AccessAcl
	}
	return 0
}

func (x *ProtoAttr) GetDefaultAcl() uint32 {
	if x != nil {
		return x.DefaultAcl
	}
	return 0
}

// Slice represents a chunk slice
type ProtoSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Off           uint32                 `protobuf:"varint,3,opt,name=off,proto3" json:"off,omitempty"`
	Len           uint32                 `protobuf:"varint,4,opt,name=len,proto3" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSlice) Reset() {
	*x = ProtoSlice{}
	mi := &file_meta_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSlice) ProtoMessage() {}

func (x *ProtoSlice) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSlice.ProtoReflect.Descriptor instead.
func (*ProtoSlice) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoSlice) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProtoSlice) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProtoSlice) GetOff() uint32 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *ProtoSlice) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

// Entry represents a directory entry
type ProtoEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attr          *ProtoAttr             `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoEntry) Reset() {
	*x = ProtoEntry{}
	mi := &file_meta_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEntry) ProtoMessage() {}

func (x *ProtoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEntry.ProtoReflect.Descriptor instead.
func (*ProtoEntry) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoEntry) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *ProtoEntry) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ProtoEntry) GetAttr() *ProtoAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

// SessionInfo for session details
type ProtoSessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	IpAddrs       []string               `protobuf:"bytes,3,rep,name=ip_addrs,json=ipAddrs,proto3" json:"ip_addrs,omitempty"`
	MountPoint    string                 `protobuf:"bytes,4,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	MountTime     int64                  `protobuf:"varint,5,opt,name=mount_time,json=mountTime,proto3" json:"mount_time,omitempty"`
	ProcessId     int32                  `protobuf:"varint,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSessionInfo) Reset() {
	*x = ProtoSessionInfo{}
	mi := &file_meta_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSessionInfo) ProtoMessage() {}

func (x *ProtoSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSessionInfo.ProtoReflect.Descriptor instead.
func (*ProtoSessionInfo) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoSessionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProtoSessionInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ProtoSessionInfo) GetIpAddrs() []string {
	if x != nil {
		return x.IpAddrs
	}
	return nil
}

func (x *ProtoSessionInfo) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *ProtoSessionInfo) GetMountTime() int64 {
	if x != nil {
		return x.MountTime
	}
	return 0
}

func (x *ProtoSessionInfo) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

// Flock for file locks
type ProtoFlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Owner         uint64                 `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Ltype         string                 `protobuf:"bytes,3,opt,name=ltype,proto3" json:"ltype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFlock) Reset() {
	*x = ProtoFlock{}
	mi := &file_meta_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFlock) ProtoMessage() {}

func (x *ProtoFlock) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFlock.ProtoReflect.Descriptor instead.
func (*ProtoFlock) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoFlock) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *ProtoFlock) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *ProtoFlock) GetLtype() string {
	if x != nil {
		return x.Ltype
	}
	return ""
}

// PlockRecord for range locks
type ProtoPlockRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Start         uint64                 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPlockRecord) Reset() {
	*x = ProtoPlockRecord{}
	mi := &file_meta_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPlockRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPlockRecord) ProtoMessage() {}

func (x *ProtoPlockRecord) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPlockRecord.ProtoReflect.Descriptor instead.
func (*ProtoPlockRecord) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoPlockRecord) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProtoPlockRecord) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProtoPlockRecord) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ProtoPlockRecord) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

// Plock for range locks
type ProtoPlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Owner         uint64                 `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Records       []*ProtoPlockRecord    `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPlock) Reset() {
	*x = ProtoPlock{}
	mi := &file_meta_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPlock) ProtoMessage() {}

func (x *ProtoPlock) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPlock.ProtoReflect.Descriptor instead.
func (*ProtoPlock) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoPlock) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *ProtoPlock) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *ProtoPlock) GetRecords() []*ProtoPlockRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// Session for client sessions
type ProtoSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	Info          *ProtoSessionInfo      `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Sustained     []uint64               `protobuf:"varint,4,rep,packed,name=sustained,proto3" json:"sustained,omitempty"`
	Flocks        []*ProtoFlock          `protobuf:"bytes,5,rep,name=flocks,proto3" json:"flocks,omitempty"`
	Plocks        []*ProtoPlock          `protobuf:"bytes,6,rep,name=plocks,proto3" json:"plocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSession) Reset() {
	*x = ProtoSession{}
	mi := &file_meta_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSession) ProtoMessage() {}

func (x *ProtoSession) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSession.ProtoReflect.Descriptor instead.
func (*ProtoSession) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoSession) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ProtoSession) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *ProtoSession) GetInfo() *ProtoSessionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ProtoSession) GetSustained() []uint64 {
	if x != nil {
		return x.Sustained
	}
	return nil
}

func (x *ProtoSession) GetFlocks() []*ProtoFlock {
	if x != nil {
		return x.Flocks
	}
	return nil
}

func (x *ProtoSession) GetPlocks() []*ProtoPlock {
	if x != nil {
		return x.Plocks
	}
	return nil
}

// Format for volume format
type ProtoFormat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid             string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Storage          string                 `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	StorageClass     string                 `protobuf:"bytes,4,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	Bucket           string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey        string                 `protobuf:"bytes,6,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey        string                 `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SessionToken     string                 `protobuf:"bytes,8,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	BlockSize        int32                  `protobuf:"varint,9,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Compression      string                 `protobuf:"bytes,10,opt,name=compression,proto3" json:"compression,omitempty"`
	Shards           int32                  `protobuf:"varint,11,opt,name=shards,proto3" json:"shards,omitempty"`
	HashPrefix       bool                   `protobuf:"varint,12,opt,name=hash_prefix,json=hashPrefix,proto3" json:"hash_prefix,omitempty"`
	Capacity         uint64                 `protobuf:"varint,13,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Inodes           uint64                 `protobuf:"varint,14,opt,name=inodes,proto3" json:"inodes,omitempty"`
	EncryptKey       string                 `protobuf:"bytes,15,opt,name=encrypt_key,json=encryptKey,proto3" json:"encrypt_key,omitempty"`
	EncryptAlgo      string                 `protobuf:"bytes,16,opt,name=encrypt_algo,json=encryptAlgo,proto3" json:"encrypt_algo,omitempty"`
	KeyEncrypted     bool                   `protobuf:"varint,17,opt,name=key_encrypted,json=keyEncrypted,proto3" json:"key_encrypted,omitempty"`
	UploadLimit      int64                  `protobuf:"varint,18,opt,name=upload_limit,json=uploadLimit,proto3" json:"upload_limit,omitempty"`
	DownloadLimit    int64                  `protobuf:"varint,19,opt,name=download_limit,json=downloadLimit,proto3" json:"download_limit,omitempty"`
	TrashDays        int32                  `protobuf:"varint,20,opt,name=trash_days,json=trashDays,proto3" json:"trash_days,omitempty"`
	MetaVersion      int32                  `protobuf:"varint,21,opt,name=meta_version,json=metaVersion,proto3" json:"meta_version,omitempty"`
	MinClientVersion string                 `protobuf:"bytes,22,opt,name=min_client_version,json=minClientVersion,proto3" json:"min_client_version,omitempty"`
	MaxClientVersion string                 `protobuf:"bytes,23,opt,name=max_client_version,json=maxClientVersion,proto3" json:"max_client_version,omitempty"`
	DirStats         bool                   `protobuf:"varint,24,opt,name=dir_stats,json=dirStats,proto3" json:"dir_stats,omitempty"`
	UserGroupQuota   bool                   `protobuf:"varint,25,opt,name=user_group_quota,json=userGroupQuota,proto3" json:"user_group_quota,omitempty"`
	EnableAcl        bool                   `protobuf:"varint,26,opt,name=enable_acl,json=enableAcl,proto3" json:"enable_acl,omitempty"`
	RangerRestUrl    string                 `protobuf:"bytes,27,opt,name=ranger_rest_url,json=rangerRestUrl,proto3" json:"ranger_rest_url,omitempty"`
	RangerService    string                 `protobuf:"bytes,28,opt,name=ranger_service,json=rangerService,proto3" json:"ranger_service,omitempty"`
	KerbConf         string                 `protobuf:"bytes,29,opt,name=kerb_conf,json=kerbConf,proto3" json:"kerb_conf,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoFormat) Reset() {
	*x = ProtoFormat{}
	mi := &file_meta_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFormat) ProtoMessage() {}

func (x *ProtoFormat) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFormat.ProtoReflect.Descriptor instead.
func (*ProtoFormat) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{9}
}

func (x *ProtoFormat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoFormat) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProtoFormat) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *ProtoFormat) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *ProtoFormat) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ProtoFormat) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *ProtoFormat) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *ProtoFormat) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ProtoFormat) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *ProtoFormat) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *ProtoFormat) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *ProtoFormat) GetHashPrefix() bool {
	if x != nil {
		return x.HashPrefix
	}
	return false
}

func (x *ProtoFormat) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ProtoFormat) GetInodes() uint64 {
	if x != nil {
		return x.Inodes
	}
	return 0
}

func (x *ProtoFormat) GetEncryptKey() string {
	if x != nil {
		return x.EncryptKey
	}
	return ""
}

func (x *ProtoFormat) GetEncryptAlgo() string {
	if x != nil {
		return x.EncryptAlgo
	}
	return ""
}

func (x *ProtoFormat) GetKeyEncrypted() bool {
	if x != nil {
		return x.KeyEncrypted
	}
	return false
}

func (x *ProtoFormat) GetUploadLimit() int64 {
	if x != nil {
		return x.UploadLimit
	}
	return 0
}

func (x *ProtoFormat) GetDownloadLimit() int64 {
	if x != nil {
		return x.DownloadLimit
	}
	return 0
}

func (x *ProtoFormat) GetTrashDays() int32 {
	if x != nil {
		return x.TrashDays
	}
	return 0
}

func (x *ProtoFormat) GetMetaVersion() int32 {
	if x != nil {
		return x.MetaVersion
	}
	return 0
}

func (x *ProtoFormat) GetMinClientVersion() string {
	if x != nil {
		return x.MinClientVersion
	}
	return ""
}

func (x *ProtoFormat) GetMaxClientVersion() string {
	if x != nil {
		return x.MaxClientVersion
	}
	return ""
}

func (x *ProtoFormat) GetDirStats() bool {
	if x != nil {
		return x.DirStats
	}
	return false
}

func (x *ProtoFormat) GetUserGroupQuota() bool {
	if x != nil {
		return x.UserGroupQuota
	}
	return false
}

func (x *ProtoFormat) GetEnableAcl() bool {
	if x != nil {
		return x.EnableAcl
	}
	return false
}

func (x *ProtoFormat) GetRangerRestUrl() string {
	if x != nil {
		return x.RangerRestUrl
	}
	return ""
}

func (x *ProtoFormat) GetRangerService() string {
	if x != nil {
		return x.RangerService
	}
	return ""
}

func (x *ProtoFormat) GetKerbConf() string {
	if x != nil {
		return x.KerbConf
	}
	return ""
}

// SliceMapEntry for map of inodes to slices
type SliceMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Slices        []*ProtoSlice          `protobuf:"bytes,2,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceMapEntry) Reset() {
	*x = SliceMapEntry{}
	mi := &file_meta_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceMapEntry) ProtoMessage() {}

func (x *SliceMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceMapEntry.ProtoReflect.Descriptor instead.
func (*SliceMapEntry) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{10}
}

func (x *SliceMapEntry) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *SliceMapEntry) GetSlices() []*ProtoSlice {
	if x != nil {
		return x.Slices
	}
	return nil
}

// Summary represents directory summary
type ProtoSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint64                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Files         uint64                 `protobuf:"varint,3,opt,name=files,proto3" json:"files,omitempty"`
	Dirs          uint64                 `protobuf:"varint,4,opt,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSummary) Reset() {
	*x = ProtoSummary{}
	mi := &file_meta_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSummary) ProtoMessage() {}

func (x *ProtoSummary) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSummary.ProtoReflect.Descriptor instead.
func (*ProtoSummary) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{11}
}

func (x *ProtoSummary) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ProtoSummary) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProtoSummary) GetFiles() uint64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *ProtoSummary) GetDirs() uint64 {
	if x != nil {
		return x.Dirs
	}
	return 0
}

// TreeSummary for recursive summary
type ProtoTreeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Files         uint64                 `protobuf:"varint,5,opt,name=files,proto3" json:"files,omitempty"`
	Dirs          uint64                 `protobuf:"varint,6,opt,name=dirs,proto3" json:"dirs,omitempty"`
	Children      []*ProtoTreeSummary    `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoTreeSummary) Reset() {
	*x = ProtoTreeSummary{}
	mi := &file_meta_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTreeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTreeSummary) ProtoMessage() {}

func (x *ProtoTreeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTreeSummary.ProtoReflect.Descriptor instead.
func (*ProtoTreeSummary) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{12}
}

func (x *ProtoTreeSummary) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *ProtoTreeSummary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProtoTreeSummary) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProtoTreeSummary) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProtoTreeSummary) GetFiles() uint64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *ProtoTreeSummary) GetDirs() uint64 {
	if x != nil {
		return x.Dirs
	}
	return 0
}

func (x *ProtoTreeSummary) GetChildren() []*ProtoTreeSummary {
	if x != nil {
		return x.Children
	}
	return nil
}

// Quota for quota management
type ProtoQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSpace      int64                  `protobuf:"varint,1,opt,name=max_space,json=maxSpace,proto3" json:"max_space,omitempty"`
	MaxInodes     int64                  `protobuf:"varint,2,opt,name=max_inodes,json=maxInodes,proto3" json:"max_inodes,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,3,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	UsedInodes    int64                  `protobuf:"varint,4,opt,name=used_inodes,json=usedInodes,proto3" json:"used_inodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoQuota) Reset() {
	*x = ProtoQuota{}
	mi := &file_meta_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoQuota) ProtoMessage() {}

func (x *ProtoQuota) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoQuota.ProtoReflect.Descriptor instead.
func (*ProtoQuota) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{13}
}

func (x *ProtoQuota) GetMaxSpace() int64 {
	if x != nil {
		return x.MaxSpace
	}
	return 0
}

func (x *ProtoQuota) GetMaxInodes() int64 {
	if x != nil {
		return x.MaxInodes
	}
	return 0
}

func (x *ProtoQuota) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *ProtoQuota) GetUsedInodes() int64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

// DirHandler handle
type DirHandlerHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      uint64                 `protobuf:"varint,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerHandle) Reset() {
	*x = DirHandlerHandle{}
	mi := &file_meta_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerHandle) ProtoMessage() {}

func (x *DirHandlerHandle) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerHandle.ProtoReflect.Descriptor instead.
func (*DirHandlerHandle) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{14}
}

func (x *DirHandlerHandle) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

// ACL Rule
type ProtoACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Perms         uint32                 `protobuf:"varint,3,opt,name=perms,proto3" json:"perms,omitempty"`
	Entries       []uint32               `protobuf:"varint,4,rep,packed,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoACLRule) Reset() {
	*x = ProtoACLRule{}
	mi := &file_meta_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoACLRule) ProtoMessage() {}

func (x *ProtoACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_meta_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoACLRule.ProtoReflect.Descriptor instead.
func (*ProtoACLRule) Descriptor() ([]byte, []int) {
	return file_meta_common_proto_rawDescGZIP(), []int{15}
}

func (x *ProtoACLRule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProtoACLRule) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProtoACLRule) GetPerms() uint32 {
	if x != nil {
		return x.Perms
	}
	return 0
}

func (x *ProtoACLRule) GetEntries() []uint32 {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_meta_common_proto protoreflect.FileDescriptor

const file_meta_common_proto_rawDesc = "" +
	"\n" +
	"\x11meta_common.proto\x12\x02pb\"\x82\x01\n" +
	"\vMetaContext\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x02 \x01(\rR\x03gid\x12\x12\n" +
	"\x04gids\x18\x03 \x03(\rR\x04gids\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12)\n" +
	"\x10check_permission\x18\x05 \x01(\bR\x0fcheckPermission\"\xd4\x03\n" +
	"\tProtoAttr\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x10\n" +
	"\x03typ\x18\x02 \x01(\rR\x03typ\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12\x12\n" +
	"\x04rdev\x18\x06 \x01(\rR\x04rdev\x12\x14\n" +
	"\x05atime\x18\a \x01(\x03R\x05atime\x12\x14\n" +
	"\x05mtime\x18\b \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05ctime\x18\t \x01(\x03R\x05ctime\x12\x1c\n" +
	"\tatimensec\x18\n" +
	" \x01(\rR\tatimensec\x12\x1c\n" +
	"\tmtimensec\x18\v \x01(\rR\tmtimensec\x12\x1c\n" +
	"\tctimensec\x18\f \x01(\rR\tctimensec\x12\x14\n" +
	"\x05nlink\x18\r \x01(\rR\x05nlink\x12\x16\n" +
	"\x06length\x18\x0e \x01(\x04R\x06length\x12\x16\n" +
	"\x06parent\x18\x0f \x01(\x04R\x06parent\x12\x12\n" +
	"\x04full\x18\x10 \x01(\bR\x04full\x12\x1d\n" +
	"\n" +
	"keep_cache\x18\x11 \x01(\bR\tkeepCache\x12\x1d\n" +
	"\n" +
	"access_acl\x18\x12 \x01(\rR\taccessAcl\x12\x1f\n" +
	"\vdefault_acl\x18\x13 \x01(\rR\n" +
	"defaultAcl\"T\n" +
	"\n" +
	"ProtoSlice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x10\n" +
	"\x03off\x18\x03 \x01(\rR\x03off\x12\x10\n" +
	"\x03len\x18\x04 \x01(\rR\x03len\"Y\n" +
	"\n" +
	"ProtoEntry\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12!\n" +
	"\x04attr\x18\x03 \x01(\v2\r.pb.ProtoAttrR\x04attr\"\xc3\x01\n" +
	"\x10ProtoSessionInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x19\n" +
	"\bip_addrs\x18\x03 \x03(\tR\aipAddrs\x12\x1f\n" +
	"\vmount_point\x18\x04 \x01(\tR\n" +
	"mountPoint\x12\x1d\n" +
	"\n" +
	"mount_time\x18\x05 \x01(\x03R\tmountTime\x12\x1d\n" +
	"\n" +
	"process_id\x18\x06 \x01(\x05R\tprocessId\"N\n" +
	"\n" +
	"ProtoFlock\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05ltype\x18\x03 \x01(\tR\x05ltype\"`\n" +
	"\x10ProtoPlockRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x04R\x03end\"h\n" +
	"\n" +
	"ProtoPlock\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\x04R\x05owner\x12.\n" +
	"\arecords\x18\x03 \x03(\v2\x14.pb.ProtoPlockRecordR\arecords\"\xd0\x01\n" +
	"\fProtoSession\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire\x12(\n" +
	"\x04info\x18\x03 \x01(\v2\x14.pb.ProtoSessionInfoR\x04info\x12\x1c\n" +
	"\tsustained\x18\x04 \x03(\x04R\tsustained\x12&\n" +
	"\x06flocks\x18\x05 \x03(\v2\x0e.pb.ProtoFlockR\x06flocks\x12&\n" +
	"\x06plocks\x18\x06 \x03(\v2\x0e.pb.ProtoPlockR\x06plocks\"\xc0\a\n" +
	"\vProtoFormat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x18\n" +
	"\astorage\x18\x03 \x01(\tR\astorage\x12#\n" +
	"\rstorage_class\x18\x04 \x01(\tR\fstorageClass\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"access_key\x18\x06 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\a \x01(\tR\tsecretKey\x12#\n" +
	"\rsession_token\x18\b \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"block_size\x18\t \x01(\x05R\tblockSize\x12 \n" +
	"\vcompression\x18\n" +
	" \x01(\tR\vcompression\x12\x16\n" +
	"\x06shards\x18\v \x01(\x05R\x06shards\x12\x1f\n" +
	"\vhash_prefix\x18\f \x01(\bR\n" +
	"hashPrefix\x12\x1a\n" +
	"\bcapacity\x18\r \x01(\x04R\bcapacity\x12\x16\n" +
	"\x06inodes\x18\x0e \x01(\x04R\x06inodes\x12\x1f\n" +
	"\vencrypt_key\x18\x0f \x01(\tR\n" +
	"encryptKey\x12!\n" +
	"\fencrypt_algo\x18\x10 \x01(\tR\vencryptAlgo\x12#\n" +
	"\rkey_encrypted\x18\x11 \x01(\bR\fkeyEncrypted\x12!\n" +
	"\fupload_limit\x18\x12 \x01(\x03R\vuploadLimit\x12%\n" +
	"\x0edownload_limit\x18\x13 \x01(\x03R\rdownloadLimit\x12\x1d\n" +
	"\n" +
	"trash_days\x18\x14 \x01(\x05R\ttrashDays\x12!\n" +
	"\fmeta_version\x18\x15 \x01(\x05R\vmetaVersion\x12,\n" +
	"\x12min_client_version\x18\x16 \x01(\tR\x10minClientVersion\x12,\n" +
	"\x12max_client_version\x18\x17 \x01(\tR\x10maxClientVersion\x12\x1b\n" +
	"\tdir_stats\x18\x18 \x01(\bR\bdirStats\x12(\n" +
	"\x10user_group_quota\x18\x19 \x01(\bR\x0euserGroupQuota\x12\x1d\n" +
	"\n" +
	"enable_acl\x18\x1a \x01(\bR\tenableAcl\x12&\n" +
	"\x0franger_rest_url\x18\x1b \x01(\tR\rrangerRestUrl\x12%\n" +
	"\x0eranger_service\x18\x1c \x01(\tR\rrangerService\x12\x1b\n" +
	"\tkerb_conf\x18\x1d \x01(\tR\bkerbConf\"M\n" +
	"\rSliceMapEntry\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12&\n" +
	"\x06slices\x18\x02 \x03(\v2\x0e.pb.ProtoSliceR\x06slices\"d\n" +
	"\fProtoSummary\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x04R\x06length\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x14\n" +
	"\x05files\x18\x03 \x01(\x04R\x05files\x12\x12\n" +
	"\x04dirs\x18\x04 \x01(\x04R\x04dirs\"\xc0\x01\n" +
	"\x10ProtoTreeSummary\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x14\n" +
	"\x05files\x18\x05 \x01(\x04R\x05files\x12\x12\n" +
	"\x04dirs\x18\x06 \x01(\x04R\x04dirs\x120\n" +
	"\bchildren\x18\a \x03(\v2\x14.pb.ProtoTreeSummaryR\bchildren\"\x88\x01\n" +
	"\n" +
	"ProtoQuota\x12\x1b\n" +
	"\tmax_space\x18\x01 \x01(\x03R\bmaxSpace\x12\x1d\n" +
	"\n" +
	"max_inodes\x18\x02 \x01(\x03R\tmaxInodes\x12\x1d\n" +
	"\n" +
	"used_space\x18\x03 \x01(\x03R\tusedSpace\x12\x1f\n" +
	"\vused_inodes\x18\x04 \x01(\x03R\n" +
	"usedInodes\"/\n" +
	"\x10DirHandlerHandle\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\x04R\bhandleId\"b\n" +
	"\fProtoACLRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x14\n" +
	"\x05perms\x18\x03 \x01(\rR\x05perms\x12\x18\n" +
	"\aentries\x18\x04 \x03(\rR\aentriesB\x06Z\x04./pbb\x06proto3"

var (
	file_meta_common_proto_rawDescOnce sync.Once
	file_meta_common_proto_rawDescData []byte
)

func file_meta_common_proto_rawDescGZIP() []byte {
	file_meta_common_proto_rawDescOnce.Do(func() {
		file_meta_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_common_proto_rawDesc), len(file_meta_common_proto_rawDesc)))
	})
	return file_meta_common_proto_rawDescData
}

var file_meta_common_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_meta_common_proto_goTypes = []any{
	(*MetaContext)(nil),      // 0: pb.MetaContext
	(*ProtoAttr)(nil),        // 1: pb.ProtoAttr
	(*ProtoSlice)(nil),       // 2: pb.ProtoSlice
	(*ProtoEntry)(nil),       // 3: pb.ProtoEntry
	(*ProtoSessionInfo)(nil), // 4: pb.ProtoSessionInfo
	(*ProtoFlock)(nil),       // 5: pb.ProtoFlock
	(*ProtoPlockRecord)(nil), // 6: pb.ProtoPlockRecord
	(*ProtoPlock)(nil),       // 7: pb.ProtoPlock
	(*ProtoSession)(nil),     // 8: pb.ProtoSession
	(*ProtoFormat)(nil),      // 9: pb.ProtoFormat
	(*SliceMapEntry)(nil),    // 10: pb.SliceMapEntry
	(*ProtoSummary)(nil),     // 11: pb.ProtoSummary
	(*ProtoTreeSummary)(nil), // 12: pb.ProtoTreeSummary
	(*ProtoQuota)(nil),       // 13: pb.ProtoQuota
	(*DirHandlerHandle)(nil), // 14: pb.DirHandlerHandle
	(*ProtoACLRule)(nil),     // 15: pb.ProtoACLRule
}
var file_meta_common_proto_depIdxs = []int32{
	1,  // 0: pb.ProtoEntry.attr:type_name -> pb.ProtoAttr
	6,  // 1: pb.ProtoPlock.records:type_name -> pb.ProtoPlockRecord
	4,  // 2: pb.ProtoSession.info:type_name -> pb.ProtoSessionInfo
	5,  // 3: pb.ProtoSession.flocks:type_name -> pb.ProtoFlock
	7,  // 4: pb.ProtoSession.plocks:type_name -> pb.ProtoPlock
	2,  // 5: pb.SliceMapEntry.slices:type_name -> pb.ProtoSlice
	12, // 6: pb.ProtoTreeSummary.children:type_name -> pb.ProtoTreeSummary
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_meta_common_proto_init() }
func file_meta_common_proto_init() {
	if File_meta_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_common_proto_rawDesc), len(file_meta_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_common_proto_goTypes,
		DependencyIndexes: file_meta_common_proto_depIdxs,
		MessageInfos:      file_meta_common_proto_msgTypes,
	}.Build()
	File_meta_common_proto = out.File
	file_meta_common_proto_goTypes = nil
	file_meta_common_proto_depIdxs = nil
}
