//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: meta_token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTokenRequest) Reset() {
	*x = StoreTokenRequest{}
	mi := &file_meta_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTokenRequest) ProtoMessage() {}

func (x *StoreTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTokenRequest.ProtoReflect.Descriptor instead.
func (*StoreTokenRequest) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{0}
}

func (x *StoreTokenRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *StoreTokenRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type StoreTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTokenResponse) Reset() {
	*x = StoreTokenResponse{}
	mi := &file_meta_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTokenResponse) ProtoMessage() {}

func (x *StoreTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTokenResponse.ProtoReflect.Descriptor instead.
func (*StoreTokenResponse) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{1}
}

func (x *StoreTokenResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *StoreTokenResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Token         []byte                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenRequest) Reset() {
	*x = UpdateTokenRequest{}
	mi := &file_meta_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenRequest) ProtoMessage() {}

func (x *UpdateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdateTokenRequest) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTokenRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *UpdateTokenRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTokenRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type UpdateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenResponse) Reset() {
	*x = UpdateTokenResponse{}
	mi := &file_meta_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenResponse) ProtoMessage() {}

func (x *UpdateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenResponse.ProtoReflect.Descriptor instead.
func (*UpdateTokenResponse) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTokenResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type LoadTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTokenRequest) Reset() {
	*x = LoadTokenRequest{}
	mi := &file_meta_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTokenRequest) ProtoMessage() {}

func (x *LoadTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTokenRequest.ProtoReflect.Descriptor instead.
func (*LoadTokenRequest) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{4}
}

func (x *LoadTokenRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *LoadTokenRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoadTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTokenResponse) Reset() {
	*x = LoadTokenResponse{}
	mi := &file_meta_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTokenResponse) ProtoMessage() {}

func (x *LoadTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTokenResponse.ProtoReflect.Descriptor instead.
func (*LoadTokenResponse) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{5}
}

func (x *LoadTokenResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *LoadTokenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type DeleteTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Ids           []uint32               `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokensRequest) Reset() {
	*x = DeleteTokensRequest{}
	mi := &file_meta_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokensRequest) ProtoMessage() {}

func (x *DeleteTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokensRequest.ProtoReflect.Descriptor instead.
func (*DeleteTokensRequest) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTokensRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *DeleteTokensRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokensResponse) Reset() {
	*x = DeleteTokensResponse{}
	mi := &file_meta_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokensResponse) ProtoMessage() {}

func (x *DeleteTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokensResponse.ProtoReflect.Descriptor instead.
func (*DeleteTokensResponse) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTokensResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_meta_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{8}
}

func (x *ListTokensRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Tokens        map[uint32][]byte      `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_meta_token_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_token_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_meta_token_proto_rawDescGZIP(), []int{9}
}

func (x *ListTokensResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ListTokensResponse) GetTokens() map[uint32][]byte {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_meta_token_proto protoreflect.FileDescriptor

const file_meta_token_proto_rawDesc = "" +
	"\n" +
	"\x10meta_token.proto\x12\x02pb\x1a\x11meta_common.proto\"L\n" +
	"\x11StoreTokenRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\":\n" +
	"\x12StoreTokenResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\"]\n" +
	"\x12UpdateTokenRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x14\n" +
	"\x05token\x18\x03 \x01(\fR\x05token\"+\n" +
	"\x13UpdateTokenResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"E\n" +
	"\x10LoadTokenRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\"?\n" +
	"\x11LoadTokenResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"J\n" +
	"\x13DeleteTokensRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\rR\x03ids\",\n" +
	"\x14DeleteTokensResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"6\n" +
	"\x11ListTokensRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\"\xa1\x01\n" +
	"\x12ListTokensResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12:\n" +
	"\x06tokens\x18\x02 \x03(\v2\".pb.ListTokensResponse.TokensEntryR\x06tokens\x1a9\n" +
	"\vTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_meta_token_proto_rawDescOnce sync.Once
	file_meta_token_proto_rawDescData []byte
)

func file_meta_token_proto_rawDescGZIP() []byte {
	file_meta_token_proto_rawDescOnce.Do(func() {
		file_meta_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_token_proto_rawDesc), len(file_meta_token_proto_rawDesc)))
	})
	return file_meta_token_proto_rawDescData
}

var file_meta_token_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_meta_token_proto_goTypes = []any{
	(*StoreTokenRequest)(nil),    // 0: pb.StoreTokenRequest
	(*StoreTokenResponse)(nil),   // 1: pb.StoreTokenResponse
	(*UpdateTokenRequest)(nil),   // 2: pb.UpdateTokenRequest
	(*UpdateTokenResponse)(nil),  // 3: pb.UpdateTokenResponse
	(*LoadTokenRequest)(nil),     // 4: pb.LoadTokenRequest
	(*LoadTokenResponse)(nil),    // 5: pb.LoadTokenResponse
	(*DeleteTokensRequest)(nil),  // 6: pb.DeleteTokensRequest
	(*DeleteTokensResponse)(nil), // 7: pb.DeleteTokensResponse
	(*ListTokensRequest)(nil),    // 8: pb.ListTokensRequest
	(*ListTokensResponse)(nil),   // 9: pb.ListTokensResponse
	nil,                          // 10: pb.ListTokensResponse.TokensEntry
	(*MetaContext)(nil),          // 11: pb.MetaContext
}
var file_meta_token_proto_depIdxs = []int32{
	11, // 0: pb.StoreTokenRequest.ctx:type_name -> pb.MetaContext
	11, // 1: pb.UpdateTokenRequest.ctx:type_name -> pb.MetaContext
	11, // 2: pb.LoadTokenRequest.ctx:type_name -> pb.MetaContext
	11, // 3: pb.DeleteTokensRequest.ctx:type_name -> pb.MetaContext
	11, // 4: pb.ListTokensRequest.ctx:type_name -> pb.MetaContext
	10, // 5: pb.ListTokensResponse.tokens:type_name -> pb.ListTokensResponse.TokensEntry
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_meta_token_proto_init() }
func file_meta_token_proto_init() {
	if File_meta_token_proto != nil {
		return
	}
	file_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_token_proto_rawDesc), len(file_meta_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_token_proto_goTypes,
		DependencyIndexes: file_meta_token_proto_depIdxs,
		MessageInfos:      file_meta_token_proto_msgTypes,
	}.Build()
	File_meta_token_proto = out.File
	file_meta_token_proto_goTypes = nil
	file_meta_token_proto_depIdxs = nil
}
