//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: pb/meta_dir_handler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewDirHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Plus          bool                   `protobuf:"varint,3,opt,name=plus,proto3" json:"plus,omitempty"`
	InitEntries   []*ProtoEntry          `protobuf:"bytes,4,rep,name=init_entries,json=initEntries,proto3" json:"init_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewDirHandlerRequest) Reset() {
	*x = NewDirHandlerRequest{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewDirHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDirHandlerRequest) ProtoMessage() {}

func (x *NewDirHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDirHandlerRequest.ProtoReflect.Descriptor instead.
func (*NewDirHandlerRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{0}
}

func (x *NewDirHandlerRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *NewDirHandlerRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *NewDirHandlerRequest) GetPlus() bool {
	if x != nil {
		return x.Plus
	}
	return false
}

func (x *NewDirHandlerRequest) GetInitEntries() []*ProtoEntry {
	if x != nil {
		return x.InitEntries
	}
	return nil
}

type NewDirHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Handle        *DirHandlerHandle      `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewDirHandlerResponse) Reset() {
	*x = NewDirHandlerResponse{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewDirHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDirHandlerResponse) ProtoMessage() {}

func (x *NewDirHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDirHandlerResponse.ProtoReflect.Descriptor instead.
func (*NewDirHandlerResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{1}
}

func (x *NewDirHandlerResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *NewDirHandlerResponse) GetHandle() *DirHandlerHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type DirHandlerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *DirHandlerHandle      `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerListRequest) Reset() {
	*x = DirHandlerListRequest{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerListRequest) ProtoMessage() {}

func (x *DirHandlerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerListRequest.ProtoReflect.Descriptor instead.
func (*DirHandlerListRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{2}
}

func (x *DirHandlerListRequest) GetHandle() *DirHandlerHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *DirHandlerListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DirHandlerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Entries       []*ProtoEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerListResponse) Reset() {
	*x = DirHandlerListResponse{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerListResponse) ProtoMessage() {}

func (x *DirHandlerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerListResponse.ProtoReflect.Descriptor instead.
func (*DirHandlerListResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{3}
}

func (x *DirHandlerListResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *DirHandlerListResponse) GetEntries() []*ProtoEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DirHandlerInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *DirHandlerHandle      `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Attr          *ProtoAttr             `protobuf:"bytes,4,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerInsertRequest) Reset() {
	*x = DirHandlerInsertRequest{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerInsertRequest) ProtoMessage() {}

func (x *DirHandlerInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerInsertRequest.ProtoReflect.Descriptor instead.
func (*DirHandlerInsertRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{4}
}

func (x *DirHandlerInsertRequest) GetHandle() *DirHandlerHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *DirHandlerInsertRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *DirHandlerInsertRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirHandlerInsertRequest) GetAttr() *ProtoAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type DirHandlerInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerInsertResponse) Reset() {
	*x = DirHandlerInsertResponse{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerInsertResponse) ProtoMessage() {}

func (x *DirHandlerInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerInsertResponse.ProtoReflect.Descriptor instead.
func (*DirHandlerInsertResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{5}
}

func (x *DirHandlerInsertResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type DirHandlerDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *DirHandlerHandle      `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerDeleteRequest) Reset() {
	*x = DirHandlerDeleteRequest{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerDeleteRequest) ProtoMessage() {}

func (x *DirHandlerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerDeleteRequest.ProtoReflect.Descriptor instead.
func (*DirHandlerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{6}
}

func (x *DirHandlerDeleteRequest) GetHandle() *DirHandlerHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *DirHandlerDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DirHandlerDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerDeleteResponse) Reset() {
	*x = DirHandlerDeleteResponse{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerDeleteResponse) ProtoMessage() {}

func (x *DirHandlerDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerDeleteResponse.ProtoReflect.Descriptor instead.
func (*DirHandlerDeleteResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{7}
}

func (x *DirHandlerDeleteResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type DirHandlerCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *DirHandlerHandle      `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerCloseRequest) Reset() {
	*x = DirHandlerCloseRequest{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerCloseRequest) ProtoMessage() {}

func (x *DirHandlerCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerCloseRequest.ProtoReflect.Descriptor instead.
func (*DirHandlerCloseRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{8}
}

func (x *DirHandlerCloseRequest) GetHandle() *DirHandlerHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type DirHandlerCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirHandlerCloseResponse) Reset() {
	*x = DirHandlerCloseResponse{}
	mi := &file_pb_meta_dir_handler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirHandlerCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirHandlerCloseResponse) ProtoMessage() {}

func (x *DirHandlerCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_dir_handler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirHandlerCloseResponse.ProtoReflect.Descriptor instead.
func (*DirHandlerCloseResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_dir_handler_proto_rawDescGZIP(), []int{9}
}

func (x *DirHandlerCloseResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

var File_pb_meta_dir_handler_proto protoreflect.FileDescriptor

const file_pb_meta_dir_handler_proto_rawDesc = "" +
	"\n" +
	"\x19pb/meta_dir_handler.proto\x12\x02pb\x1a\x14pb/meta_common.proto\"\x96\x01\n" +
	"\x14NewDirHandlerRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04plus\x18\x03 \x01(\bR\x04plus\x121\n" +
	"\finit_entries\x18\x04 \x03(\v2\x0e.pb.ProtoEntryR\vinitEntries\"[\n" +
	"\x15NewDirHandlerResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12,\n" +
	"\x06handle\x18\x02 \x01(\v2\x14.pb.DirHandlerHandleR\x06handle\"]\n" +
	"\x15DirHandlerListRequest\x12,\n" +
	"\x06handle\x18\x01 \x01(\v2\x14.pb.DirHandlerHandleR\x06handle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"X\n" +
	"\x16DirHandlerListResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12(\n" +
	"\aentries\x18\x02 \x03(\v2\x0e.pb.ProtoEntryR\aentries\"\x94\x01\n" +
	"\x17DirHandlerInsertRequest\x12,\n" +
	"\x06handle\x18\x01 \x01(\v2\x14.pb.DirHandlerHandleR\x06handle\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\x04attr\x18\x04 \x01(\v2\r.pb.ProtoAttrR\x04attr\"0\n" +
	"\x18DirHandlerInsertResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"[\n" +
	"\x17DirHandlerDeleteRequest\x12,\n" +
	"\x06handle\x18\x01 \x01(\v2\x14.pb.DirHandlerHandleR\x06handle\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"0\n" +
	"\x18DirHandlerDeleteResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"F\n" +
	"\x16DirHandlerCloseRequest\x12,\n" +
	"\x06handle\x18\x01 \x01(\v2\x14.pb.DirHandlerHandleR\x06handle\"/\n" +
	"\x17DirHandlerCloseResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errnoB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_meta_dir_handler_proto_rawDescOnce sync.Once
	file_pb_meta_dir_handler_proto_rawDescData []byte
)

func file_pb_meta_dir_handler_proto_rawDescGZIP() []byte {
	file_pb_meta_dir_handler_proto_rawDescOnce.Do(func() {
		file_pb_meta_dir_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_meta_dir_handler_proto_rawDesc), len(file_pb_meta_dir_handler_proto_rawDesc)))
	})
	return file_pb_meta_dir_handler_proto_rawDescData
}

var file_pb_meta_dir_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_meta_dir_handler_proto_goTypes = []any{
	(*NewDirHandlerRequest)(nil),     // 0: pb.NewDirHandlerRequest
	(*NewDirHandlerResponse)(nil),    // 1: pb.NewDirHandlerResponse
	(*DirHandlerListRequest)(nil),    // 2: pb.DirHandlerListRequest
	(*DirHandlerListResponse)(nil),   // 3: pb.DirHandlerListResponse
	(*DirHandlerInsertRequest)(nil),  // 4: pb.DirHandlerInsertRequest
	(*DirHandlerInsertResponse)(nil), // 5: pb.DirHandlerInsertResponse
	(*DirHandlerDeleteRequest)(nil),  // 6: pb.DirHandlerDeleteRequest
	(*DirHandlerDeleteResponse)(nil), // 7: pb.DirHandlerDeleteResponse
	(*DirHandlerCloseRequest)(nil),   // 8: pb.DirHandlerCloseRequest
	(*DirHandlerCloseResponse)(nil),  // 9: pb.DirHandlerCloseResponse
	(*MetaContext)(nil),              // 10: pb.MetaContext
	(*ProtoEntry)(nil),               // 11: pb.ProtoEntry
	(*DirHandlerHandle)(nil),         // 12: pb.DirHandlerHandle
	(*ProtoAttr)(nil),                // 13: pb.ProtoAttr
}
var file_pb_meta_dir_handler_proto_depIdxs = []int32{
	10, // 0: pb.NewDirHandlerRequest.ctx:type_name -> pb.MetaContext
	11, // 1: pb.NewDirHandlerRequest.init_entries:type_name -> pb.ProtoEntry
	12, // 2: pb.NewDirHandlerResponse.handle:type_name -> pb.DirHandlerHandle
	12, // 3: pb.DirHandlerListRequest.handle:type_name -> pb.DirHandlerHandle
	11, // 4: pb.DirHandlerListResponse.entries:type_name -> pb.ProtoEntry
	12, // 5: pb.DirHandlerInsertRequest.handle:type_name -> pb.DirHandlerHandle
	13, // 6: pb.DirHandlerInsertRequest.attr:type_name -> pb.ProtoAttr
	12, // 7: pb.DirHandlerDeleteRequest.handle:type_name -> pb.DirHandlerHandle
	12, // 8: pb.DirHandlerCloseRequest.handle:type_name -> pb.DirHandlerHandle
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pb_meta_dir_handler_proto_init() }
func file_pb_meta_dir_handler_proto_init() {
	if File_pb_meta_dir_handler_proto != nil {
		return
	}
	file_pb_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_meta_dir_handler_proto_rawDesc), len(file_pb_meta_dir_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_meta_dir_handler_proto_goTypes,
		DependencyIndexes: file_pb_meta_dir_handler_proto_depIdxs,
		MessageInfos:      file_pb_meta_dir_handler_proto_msgTypes,
	}.Build()
	File_pb_meta_dir_handler_proto = out.File
	file_pb_meta_dir_handler_proto_goTypes = nil
	file_pb_meta_dir_handler_proto_depIdxs = nil
}
