//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: meta_acl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetFaclRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Ino           uint64                 `protobuf:"varint,2,opt,name=ino,proto3" json:"ino,omitempty"`
	AclType       uint32                 `protobuf:"varint,3,opt,name=acl_type,json=aclType,proto3" json:"acl_type,omitempty"`
	Rule          *ProtoACLRule          `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFaclRequest) Reset() {
	*x = SetFaclRequest{}
	mi := &file_meta_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFaclRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFaclRequest) ProtoMessage() {}

func (x *SetFaclRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFaclRequest.ProtoReflect.Descriptor instead.
func (*SetFaclRequest) Descriptor() ([]byte, []int) {
	return file_meta_acl_proto_rawDescGZIP(), []int{0}
}

func (x *SetFaclRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *SetFaclRequest) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *SetFaclRequest) GetAclType() uint32 {
	if x != nil {
		return x.AclType
	}
	return 0
}

func (x *SetFaclRequest) GetRule() *ProtoACLRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type SetFaclResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFaclResponse) Reset() {
	*x = SetFaclResponse{}
	mi := &file_meta_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFaclResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFaclResponse) ProtoMessage() {}

func (x *SetFaclResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFaclResponse.ProtoReflect.Descriptor instead.
func (*SetFaclResponse) Descriptor() ([]byte, []int) {
	return file_meta_acl_proto_rawDescGZIP(), []int{1}
}

func (x *SetFaclResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type GetFaclRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Ino           uint64                 `protobuf:"varint,2,opt,name=ino,proto3" json:"ino,omitempty"`
	AclType       uint32                 `protobuf:"varint,3,opt,name=acl_type,json=aclType,proto3" json:"acl_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFaclRequest) Reset() {
	*x = GetFaclRequest{}
	mi := &file_meta_acl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaclRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaclRequest) ProtoMessage() {}

func (x *GetFaclRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_acl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaclRequest.ProtoReflect.Descriptor instead.
func (*GetFaclRequest) Descriptor() ([]byte, []int) {
	return file_meta_acl_proto_rawDescGZIP(), []int{2}
}

func (x *GetFaclRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetFaclRequest) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *GetFaclRequest) GetAclType() uint32 {
	if x != nil {
		return x.AclType
	}
	return 0
}

type GetFaclResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Rule          *ProtoACLRule          `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFaclResponse) Reset() {
	*x = GetFaclResponse{}
	mi := &file_meta_acl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaclResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaclResponse) ProtoMessage() {}

func (x *GetFaclResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_acl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaclResponse.ProtoReflect.Descriptor instead.
func (*GetFaclResponse) Descriptor() ([]byte, []int) {
	return file_meta_acl_proto_rawDescGZIP(), []int{3}
}

func (x *GetFaclResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetFaclResponse) GetRule() *ProtoACLRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_meta_acl_proto protoreflect.FileDescriptor

const file_meta_acl_proto_rawDesc = "" +
	"\n" +
	"\x0emeta_acl.proto\x12\x02pb\x1a\x11meta_common.proto\"\x86\x01\n" +
	"\x0eSetFaclRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x10\n" +
	"\x03ino\x18\x02 \x01(\x04R\x03ino\x12\x19\n" +
	"\bacl_type\x18\x03 \x01(\rR\aaclType\x12$\n" +
	"\x04rule\x18\x04 \x01(\v2\x10.pb.ProtoACLRuleR\x04rule\"'\n" +
	"\x0fSetFaclResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"`\n" +
	"\x0eGetFaclRequest\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x10\n" +
	"\x03ino\x18\x02 \x01(\x04R\x03ino\x12\x19\n" +
	"\bacl_type\x18\x03 \x01(\rR\aaclType\"M\n" +
	"\x0fGetFaclResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12$\n" +
	"\x04rule\x18\x02 \x01(\v2\x10.pb.ProtoACLRuleR\x04ruleB\x06Z\x04./pbb\x06proto3"

var (
	file_meta_acl_proto_rawDescOnce sync.Once
	file_meta_acl_proto_rawDescData []byte
)

func file_meta_acl_proto_rawDescGZIP() []byte {
	file_meta_acl_proto_rawDescOnce.Do(func() {
		file_meta_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_acl_proto_rawDesc), len(file_meta_acl_proto_rawDesc)))
	})
	return file_meta_acl_proto_rawDescData
}

var file_meta_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_meta_acl_proto_goTypes = []any{
	(*SetFaclRequest)(nil),  // 0: pb.SetFaclRequest
	(*SetFaclResponse)(nil), // 1: pb.SetFaclResponse
	(*GetFaclRequest)(nil),  // 2: pb.GetFaclRequest
	(*GetFaclResponse)(nil), // 3: pb.GetFaclResponse
	(*MetaContext)(nil),     // 4: pb.MetaContext
	(*ProtoACLRule)(nil),    // 5: pb.ProtoACLRule
}
var file_meta_acl_proto_depIdxs = []int32{
	4, // 0: pb.SetFaclRequest.ctx:type_name -> pb.MetaContext
	5, // 1: pb.SetFaclRequest.rule:type_name -> pb.ProtoACLRule
	4, // 2: pb.GetFaclRequest.ctx:type_name -> pb.MetaContext
	5, // 3: pb.GetFaclResponse.rule:type_name -> pb.ProtoACLRule
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_meta_acl_proto_init() }
func file_meta_acl_proto_init() {
	if File_meta_acl_proto != nil {
		return
	}
	file_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_acl_proto_rawDesc), len(file_meta_acl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_acl_proto_goTypes,
		DependencyIndexes: file_meta_acl_proto_depIdxs,
		MessageInfos:      file_meta_acl_proto_msgTypes,
	}.Build()
	File_meta_acl_proto = out.File
	file_meta_acl_proto_goTypes = nil
	file_meta_acl_proto_depIdxs = nil
}
