//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: meta_streaming.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DumpMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          uint64                 `protobuf:"varint,1,opt,name=root,proto3" json:"root,omitempty"`
	Threads       int32                  `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	KeepSecret    bool                   `protobuf:"varint,3,opt,name=keep_secret,json=keepSecret,proto3" json:"keep_secret,omitempty"`
	Fast          bool                   `protobuf:"varint,4,opt,name=fast,proto3" json:"fast,omitempty"`
	SkipTrash     bool                   `protobuf:"varint,5,opt,name=skip_trash,json=skipTrash,proto3" json:"skip_trash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpMetaRequest) Reset() {
	*x = DumpMetaRequest{}
	mi := &file_meta_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpMetaRequest) ProtoMessage() {}

func (x *DumpMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpMetaRequest.ProtoReflect.Descriptor instead.
func (*DumpMetaRequest) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *DumpMetaRequest) GetRoot() uint64 {
	if x != nil {
		return x.Root
	}
	return 0
}

func (x *DumpMetaRequest) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *DumpMetaRequest) GetKeepSecret() bool {
	if x != nil {
		return x.KeepSecret
	}
	return false
}

func (x *DumpMetaRequest) GetFast() bool {
	if x != nil {
		return x.Fast
	}
	return false
}

func (x *DumpMetaRequest) GetSkipTrash() bool {
	if x != nil {
		return x.SkipTrash
	}
	return false
}

type DumpMetaChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpMetaChunk) Reset() {
	*x = DumpMetaChunk{}
	mi := &file_meta_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpMetaChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpMetaChunk) ProtoMessage() {}

func (x *DumpMetaChunk) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpMetaChunk.ProtoReflect.Descriptor instead.
func (*DumpMetaChunk) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *DumpMetaChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadMetaChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMetaChunk) Reset() {
	*x = LoadMetaChunk{}
	mi := &file_meta_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMetaChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetaChunk) ProtoMessage() {}

func (x *LoadMetaChunk) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetaChunk.ProtoReflect.Descriptor instead.
func (*LoadMetaChunk) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *LoadMetaChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMetaResponse) Reset() {
	*x = LoadMetaResponse{}
	mi := &file_meta_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetaResponse) ProtoMessage() {}

func (x *LoadMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetaResponse.ProtoReflect.Descriptor instead.
func (*LoadMetaResponse) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *LoadMetaResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type DumpMetaV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	KeepSecret    bool                   `protobuf:"varint,2,opt,name=keep_secret,json=keepSecret,proto3" json:"keep_secret,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpMetaV2Request) Reset() {
	*x = DumpMetaV2Request{}
	mi := &file_meta_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpMetaV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpMetaV2Request) ProtoMessage() {}

func (x *DumpMetaV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpMetaV2Request.ProtoReflect.Descriptor instead.
func (*DumpMetaV2Request) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *DumpMetaV2Request) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *DumpMetaV2Request) GetKeepSecret() bool {
	if x != nil {
		return x.KeepSecret
	}
	return false
}

func (x *DumpMetaV2Request) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type DumpMetaV2Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpMetaV2Chunk) Reset() {
	*x = DumpMetaV2Chunk{}
	mi := &file_meta_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpMetaV2Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpMetaV2Chunk) ProtoMessage() {}

func (x *DumpMetaV2Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpMetaV2Chunk.ProtoReflect.Descriptor instead.
func (*DumpMetaV2Chunk) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *DumpMetaV2Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadMetaV2Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMetaV2Chunk) Reset() {
	*x = LoadMetaV2Chunk{}
	mi := &file_meta_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMetaV2Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetaV2Chunk) ProtoMessage() {}

func (x *LoadMetaV2Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetaV2Chunk.ProtoReflect.Descriptor instead.
func (*LoadMetaV2Chunk) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *LoadMetaV2Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadMetaV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMetaV2Response) Reset() {
	*x = LoadMetaV2Response{}
	mi := &file_meta_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMetaV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetaV2Response) ProtoMessage() {}

func (x *LoadMetaV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetaV2Response.ProtoReflect.Descriptor instead.
func (*LoadMetaV2Response) Descriptor() ([]byte, []int) {
	return file_meta_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *LoadMetaV2Response) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

var File_meta_streaming_proto protoreflect.FileDescriptor

const file_meta_streaming_proto_rawDesc = "" +
	"\n" +
	"\x14meta_streaming.proto\x12\x02pb\x1a\x11meta_common.proto\"\x93\x01\n" +
	"\x0fDumpMetaRequest\x12\x12\n" +
	"\x04root\x18\x01 \x01(\x04R\x04root\x12\x18\n" +
	"\athreads\x18\x02 \x01(\x05R\athreads\x12\x1f\n" +
	"\vkeep_secret\x18\x03 \x01(\bR\n" +
	"keepSecret\x12\x12\n" +
	"\x04fast\x18\x04 \x01(\bR\x04fast\x12\x1d\n" +
	"\n" +
	"skip_trash\x18\x05 \x01(\bR\tskipTrash\"#\n" +
	"\rDumpMetaChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\rLoadMetaChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"(\n" +
	"\x10LoadMetaResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"q\n" +
	"\x11DumpMetaV2Request\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.pb.MetaContextR\x03ctx\x12\x1f\n" +
	"\vkeep_secret\x18\x02 \x01(\bR\n" +
	"keepSecret\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\"%\n" +
	"\x0fDumpMetaV2Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fLoadMetaV2Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"*\n" +
	"\x12LoadMetaV2Response\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errnoB\x06Z\x04./pbb\x06proto3"

var (
	file_meta_streaming_proto_rawDescOnce sync.Once
	file_meta_streaming_proto_rawDescData []byte
)

func file_meta_streaming_proto_rawDescGZIP() []byte {
	file_meta_streaming_proto_rawDescOnce.Do(func() {
		file_meta_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_streaming_proto_rawDesc), len(file_meta_streaming_proto_rawDesc)))
	})
	return file_meta_streaming_proto_rawDescData
}

var file_meta_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_meta_streaming_proto_goTypes = []any{
	(*DumpMetaRequest)(nil),    // 0: pb.DumpMetaRequest
	(*DumpMetaChunk)(nil),      // 1: pb.DumpMetaChunk
	(*LoadMetaChunk)(nil),      // 2: pb.LoadMetaChunk
	(*LoadMetaResponse)(nil),   // 3: pb.LoadMetaResponse
	(*DumpMetaV2Request)(nil),  // 4: pb.DumpMetaV2Request
	(*DumpMetaV2Chunk)(nil),    // 5: pb.DumpMetaV2Chunk
	(*LoadMetaV2Chunk)(nil),    // 6: pb.LoadMetaV2Chunk
	(*LoadMetaV2Response)(nil), // 7: pb.LoadMetaV2Response
	(*MetaContext)(nil),        // 8: pb.MetaContext
}
var file_meta_streaming_proto_depIdxs = []int32{
	8, // 0: pb.DumpMetaV2Request.ctx:type_name -> pb.MetaContext
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meta_streaming_proto_init() }
func file_meta_streaming_proto_init() {
	if File_meta_streaming_proto != nil {
		return
	}
	file_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_streaming_proto_rawDesc), len(file_meta_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_streaming_proto_goTypes,
		DependencyIndexes: file_meta_streaming_proto_depIdxs,
		MessageInfos:      file_meta_streaming_proto_msgTypes,
	}.Build()
	File_meta_streaming_proto = out.File
	file_meta_streaming_proto_goTypes = nil
	file_meta_streaming_proto_depIdxs = nil
}
