//
// JuiceFS, Copyright 2026 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sts_proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StsCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StsCredentialsRequest) Reset() {
	*x = StsCredentialsRequest{}
	mi := &file_sts_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StsCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StsCredentialsRequest) ProtoMessage() {}

func (x *StsCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StsCredentialsRequest.ProtoReflect.Descriptor instead.
func (*StsCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_sts_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *StsCredentialsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type StsCredentialsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpirationUnix  int64                  `protobuf:"varint,4,opt,name=expiration_unix,json=expirationUnix,proto3" json:"expiration_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StsCredentialsResponse) Reset() {
	*x = StsCredentialsResponse{}
	mi := &file_sts_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StsCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StsCredentialsResponse) ProtoMessage() {}

func (x *StsCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StsCredentialsResponse.ProtoReflect.Descriptor instead.
func (*StsCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_sts_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *StsCredentialsResponse) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *StsCredentialsResponse) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *StsCredentialsResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *StsCredentialsResponse) GetExpirationUnix() int64 {
	if x != nil {
		return x.ExpirationUnix
	}
	return 0
}

var File_sts_proxy_proto protoreflect.FileDescriptor

const file_sts_proxy_proto_rawDesc = "" +
	"\n" +
	"\x0fsts_proxy.proto\x12\x02pb\"6\n" +
	"\x15StsCredentialsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"\xb6\x01\n" +
	"\x16StsCredentialsResponse\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12'\n" +
	"\x0fexpiration_unix\x18\x04 \x01(\x03R\x0eexpirationUnix2]\n" +
	"\x0fStsProxyService\x12J\n" +
	"\x11GetSTSCredentials\x12\x19.pb.StsCredentialsRequest\x1a\x1a.pb.StsCredentialsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_sts_proxy_proto_rawDescOnce sync.Once
	file_sts_proxy_proto_rawDescData []byte
)

func file_sts_proxy_proto_rawDescGZIP() []byte {
	file_sts_proxy_proto_rawDescOnce.Do(func() {
		file_sts_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sts_proxy_proto_rawDesc), len(file_sts_proxy_proto_rawDesc)))
	})
	return file_sts_proxy_proto_rawDescData
}

var file_sts_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sts_proxy_proto_goTypes = []any{
	(*StsCredentialsRequest)(nil),  // 0: pb.StsCredentialsRequest
	(*StsCredentialsResponse)(nil), // 1: pb.StsCredentialsResponse
}
var file_sts_proxy_proto_depIdxs = []int32{
	0, // 0: pb.StsProxyService.GetSTSCredentials:input_type -> pb.StsCredentialsRequest
	1, // 1: pb.StsProxyService.GetSTSCredentials:output_type -> pb.StsCredentialsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sts_proxy_proto_init() }
func file_sts_proxy_proto_init() {
	if File_sts_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sts_proxy_proto_rawDesc), len(file_sts_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sts_proxy_proto_goTypes,
		DependencyIndexes: file_sts_proxy_proto_depIdxs,
		MessageInfos:      file_sts_proxy_proto_msgTypes,
	}.Build()
	File_sts_proxy_proto = out.File
	file_sts_proxy_proto_goTypes = nil
	file_sts_proxy_proto_depIdxs = nil
}
