//
// JuiceFS, Copyright 2026 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sts_proxy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StsProxyService_GetSTSCredentials_FullMethodName = "/pb.StsProxyService/GetSTSCredentials"
)

// StsProxyServiceClient is the client API for StsProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StsProxyService is the user-path pass-through for short-lived S3 storage
// credentials (task 7.12, ADR-003): the Meta Proxy forwards the request to the
// platform KeyManager, filling user_id from the authenticated OIDC session —
// the client never names the identity. KeyManager stays internal (proxy-trust
// model, as for the file FEK RPCs).
type StsProxyServiceClient interface {
	// GetSTSCredentials returns volume-scoped short-lived S3 credentials for the
	// authenticated session (FR-REV-3, ADR-003). The proxy fills user_id from the
	// authenticated OIDC session; any client-supplied identity is ignored.
	GetSTSCredentials(ctx context.Context, in *StsCredentialsRequest, opts ...grpc.CallOption) (*StsCredentialsResponse, error)
}

type stsProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStsProxyServiceClient(cc grpc.ClientConnInterface) StsProxyServiceClient {
	return &stsProxyServiceClient{cc}
}

func (c *stsProxyServiceClient) GetSTSCredentials(ctx context.Context, in *StsCredentialsRequest, opts ...grpc.CallOption) (*StsCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StsCredentialsResponse)
	err := c.cc.Invoke(ctx, StsProxyService_GetSTSCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StsProxyServiceServer is the server API for StsProxyService service.
// All implementations must embed UnimplementedStsProxyServiceServer
// for forward compatibility.
//
// StsProxyService is the user-path pass-through for short-lived S3 storage
// credentials (task 7.12, ADR-003): the Meta Proxy forwards the request to the
// platform KeyManager, filling user_id from the authenticated OIDC session —
// the client never names the identity. KeyManager stays internal (proxy-trust
// model, as for the file FEK RPCs).
type StsProxyServiceServer interface {
	// GetSTSCredentials returns volume-scoped short-lived S3 credentials for the
	// authenticated session (FR-REV-3, ADR-003). The proxy fills user_id from the
	// authenticated OIDC session; any client-supplied identity is ignored.
	GetSTSCredentials(context.Context, *StsCredentialsRequest) (*StsCredentialsResponse, error)
	mustEmbedUnimplementedStsProxyServiceServer()
}

// UnimplementedStsProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStsProxyServiceServer struct{}

func (UnimplementedStsProxyServiceServer) GetSTSCredentials(context.Context, *StsCredentialsRequest) (*StsCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSTSCredentials not implemented")
}
func (UnimplementedStsProxyServiceServer) mustEmbedUnimplementedStsProxyServiceServer() {}
func (UnimplementedStsProxyServiceServer) testEmbeddedByValue()                         {}

// UnsafeStsProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StsProxyServiceServer will
// result in compilation errors.
type UnsafeStsProxyServiceServer interface {
	mustEmbedUnimplementedStsProxyServiceServer()
}

func RegisterStsProxyServiceServer(s grpc.ServiceRegistrar, srv StsProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedStsProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StsProxyService_ServiceDesc, srv)
}

func _StsProxyService_GetSTSCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StsCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StsProxyServiceServer).GetSTSCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StsProxyService_GetSTSCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StsProxyServiceServer).GetSTSCredentials(ctx, req.(*StsCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StsProxyService_ServiceDesc is the grpc.ServiceDesc for StsProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StsProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StsProxyService",
	HandlerType: (*StsProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSTSCredentials",
			Handler:    _StsProxyService_GetSTSCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sts_proxy.proto",
}
