//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: meta_locks.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Owner         uint64                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Ltype         uint32                 `protobuf:"varint,4,opt,name=ltype,proto3" json:"ltype,omitempty"`
	Block         bool                   `protobuf:"varint,5,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlockRequest) Reset() {
	*x = FlockRequest{}
	mi := &file_meta_locks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlockRequest) ProtoMessage() {}

func (x *FlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlockRequest.ProtoReflect.Descriptor instead.
func (*FlockRequest) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{0}
}

func (x *FlockRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *FlockRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FlockRequest) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *FlockRequest) GetLtype() uint32 {
	if x != nil {
		return x.Ltype
	}
	return 0
}

func (x *FlockRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type FlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlockResponse) Reset() {
	*x = FlockResponse{}
	mi := &file_meta_locks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlockResponse) ProtoMessage() {}

func (x *FlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlockResponse.ProtoReflect.Descriptor instead.
func (*FlockResponse) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{1}
}

func (x *FlockResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type GetlkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Owner         uint64                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Ltype         uint32                 `protobuf:"varint,4,opt,name=ltype,proto3" json:"ltype,omitempty"`
	Start         uint64                 `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,6,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetlkRequest) Reset() {
	*x = GetlkRequest{}
	mi := &file_meta_locks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetlkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetlkRequest) ProtoMessage() {}

func (x *GetlkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetlkRequest.ProtoReflect.Descriptor instead.
func (*GetlkRequest) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{2}
}

func (x *GetlkRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetlkRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *GetlkRequest) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *GetlkRequest) GetLtype() uint32 {
	if x != nil {
		return x.Ltype
	}
	return 0
}

func (x *GetlkRequest) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetlkRequest) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type GetlkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Ltype         uint32                 `protobuf:"varint,2,opt,name=ltype,proto3" json:"ltype,omitempty"`
	Start         uint64                 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Pid           uint32                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetlkResponse) Reset() {
	*x = GetlkResponse{}
	mi := &file_meta_locks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetlkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetlkResponse) ProtoMessage() {}

func (x *GetlkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetlkResponse.ProtoReflect.Descriptor instead.
func (*GetlkResponse) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{3}
}

func (x *GetlkResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetlkResponse) GetLtype() uint32 {
	if x != nil {
		return x.Ltype
	}
	return 0
}

func (x *GetlkResponse) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetlkResponse) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GetlkResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SetlkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Owner         uint64                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Block         bool                   `protobuf:"varint,4,opt,name=block,proto3" json:"block,omitempty"`
	Ltype         uint32                 `protobuf:"varint,5,opt,name=ltype,proto3" json:"ltype,omitempty"`
	Start         uint64                 `protobuf:"varint,6,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,7,opt,name=end,proto3" json:"end,omitempty"`
	Pid           uint32                 `protobuf:"varint,8,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetlkRequest) Reset() {
	*x = SetlkRequest{}
	mi := &file_meta_locks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetlkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetlkRequest) ProtoMessage() {}

func (x *SetlkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetlkRequest.ProtoReflect.Descriptor instead.
func (*SetlkRequest) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{4}
}

func (x *SetlkRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *SetlkRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *SetlkRequest) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *SetlkRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *SetlkRequest) GetLtype() uint32 {
	if x != nil {
		return x.Ltype
	}
	return 0
}

func (x *SetlkRequest) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SetlkRequest) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *SetlkRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SetlkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetlkResponse) Reset() {
	*x = SetlkResponse{}
	mi := &file_meta_locks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetlkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetlkResponse) ProtoMessage() {}

func (x *SetlkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetlkResponse.ProtoReflect.Descriptor instead.
func (*SetlkResponse) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{5}
}

func (x *SetlkResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ListLocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocksRequest) Reset() {
	*x = ListLocksRequest{}
	mi := &file_meta_locks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksRequest) ProtoMessage() {}

func (x *ListLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksRequest.ProtoReflect.Descriptor instead.
func (*ListLocksRequest) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{6}
}

func (x *ListLocksRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ListLocksRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type ListLocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Plocks        []*ProtoPlock          `protobuf:"bytes,2,rep,name=plocks,proto3" json:"plocks,omitempty"`
	Flocks        []*ProtoFlock          `protobuf:"bytes,3,rep,name=flocks,proto3" json:"flocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocksResponse) Reset() {
	*x = ListLocksResponse{}
	mi := &file_meta_locks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksResponse) ProtoMessage() {}

func (x *ListLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_locks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksResponse.ProtoReflect.Descriptor instead.
func (*ListLocksResponse) Descriptor() ([]byte, []int) {
	return file_meta_locks_proto_rawDescGZIP(), []int{7}
}

func (x *ListLocksResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ListLocksResponse) GetPlocks() []*ProtoPlock {
	if x != nil {
		return x.Plocks
	}
	return nil
}

func (x *ListLocksResponse) GetFlocks() []*ProtoFlock {
	if x != nil {
		return x.Flocks
	}
	return nil
}

var File_meta_locks_proto protoreflect.FileDescriptor

const file_meta_locks_proto_rawDesc = "" +
	"\n" +
	"\x10meta_locks.proto\x12\x04meta\x1a\x11meta_common.proto\"\x8b\x01\n" +
	"\fFlockRequest\x12#\n" +
	"\x03ctx\x18\x01 \x01(\v2\x11.meta.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05ltype\x18\x04 \x01(\rR\x05ltype\x12\x14\n" +
	"\x05block\x18\x05 \x01(\bR\x05block\"%\n" +
	"\rFlockResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"\x9d\x01\n" +
	"\fGetlkRequest\x12#\n" +
	"\x03ctx\x18\x01 \x01(\v2\x11.meta.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05ltype\x18\x04 \x01(\rR\x05ltype\x12\x14\n" +
	"\x05start\x18\x05 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x06 \x01(\x04R\x03end\"u\n" +
	"\rGetlkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x14\n" +
	"\x05ltype\x18\x02 \x01(\rR\x05ltype\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x04R\x03end\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\rR\x03pid\"\xc5\x01\n" +
	"\fSetlkRequest\x12#\n" +
	"\x03ctx\x18\x01 \x01(\v2\x11.meta.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05block\x18\x04 \x01(\bR\x05block\x12\x14\n" +
	"\x05ltype\x18\x05 \x01(\rR\x05ltype\x12\x14\n" +
	"\x05start\x18\x06 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\a \x01(\x04R\x03end\x12\x10\n" +
	"\x03pid\x18\b \x01(\rR\x03pid\"%\n" +
	"\rSetlkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\"M\n" +
	"\x10ListLocksRequest\x12#\n" +
	"\x03ctx\x18\x01 \x01(\v2\x11.meta.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\"}\n" +
	"\x11ListLocksResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12(\n" +
	"\x06plocks\x18\x02 \x03(\v2\x10.meta.ProtoPlockR\x06plocks\x12(\n" +
	"\x06flocks\x18\x03 \x03(\v2\x10.meta.ProtoFlockR\x06flocksB,Z*github.com/juicedata/juicefs/pkg/meta/grpcb\x06proto3"

var (
	file_meta_locks_proto_rawDescOnce sync.Once
	file_meta_locks_proto_rawDescData []byte
)

func file_meta_locks_proto_rawDescGZIP() []byte {
	file_meta_locks_proto_rawDescOnce.Do(func() {
		file_meta_locks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_locks_proto_rawDesc), len(file_meta_locks_proto_rawDesc)))
	})
	return file_meta_locks_proto_rawDescData
}

var file_meta_locks_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_meta_locks_proto_goTypes = []any{
	(*FlockRequest)(nil),      // 0: meta.FlockRequest
	(*FlockResponse)(nil),     // 1: meta.FlockResponse
	(*GetlkRequest)(nil),      // 2: meta.GetlkRequest
	(*GetlkResponse)(nil),     // 3: meta.GetlkResponse
	(*SetlkRequest)(nil),      // 4: meta.SetlkRequest
	(*SetlkResponse)(nil),     // 5: meta.SetlkResponse
	(*ListLocksRequest)(nil),  // 6: meta.ListLocksRequest
	(*ListLocksResponse)(nil), // 7: meta.ListLocksResponse
	(*MetaContext)(nil),       // 8: meta.MetaContext
	(*ProtoPlock)(nil),        // 9: meta.ProtoPlock
	(*ProtoFlock)(nil),        // 10: meta.ProtoFlock
}
var file_meta_locks_proto_depIdxs = []int32{
	8,  // 0: meta.FlockRequest.ctx:type_name -> meta.MetaContext
	8,  // 1: meta.GetlkRequest.ctx:type_name -> meta.MetaContext
	8,  // 2: meta.SetlkRequest.ctx:type_name -> meta.MetaContext
	8,  // 3: meta.ListLocksRequest.ctx:type_name -> meta.MetaContext
	9,  // 4: meta.ListLocksResponse.plocks:type_name -> meta.ProtoPlock
	10, // 5: meta.ListLocksResponse.flocks:type_name -> meta.ProtoFlock
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_meta_locks_proto_init() }
func file_meta_locks_proto_init() {
	if File_meta_locks_proto != nil {
		return
	}
	file_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_locks_proto_rawDesc), len(file_meta_locks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_locks_proto_goTypes,
		DependencyIndexes: file_meta_locks_proto_depIdxs,
		MessageInfos:      file_meta_locks_proto_msgTypes,
	}.Build()
	File_meta_locks_proto = out.File
	file_meta_locks_proto_goTypes = nil
	file_meta_locks_proto_depIdxs = nil
}
