//
// JuiceFS, Copyright 2021 Juicedata, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: meta_directory.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetParentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentsRequest) Reset() {
	*x = GetParentsRequest{}
	mi := &file_meta_directory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentsRequest) ProtoMessage() {}

func (x *GetParentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_directory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentsRequest.ProtoReflect.Descriptor instead.
func (*GetParentsRequest) Descriptor() ([]byte, []int) {
	return file_meta_directory_proto_rawDescGZIP(), []int{0}
}

func (x *GetParentsRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetParentsRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type GetParentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Parents       map[uint64]int32       `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentsResponse) Reset() {
	*x = GetParentsResponse{}
	mi := &file_meta_directory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentsResponse) ProtoMessage() {}

func (x *GetParentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_directory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentsResponse.ProtoReflect.Descriptor instead.
func (*GetParentsResponse) Descriptor() ([]byte, []int) {
	return file_meta_directory_proto_rawDescGZIP(), []int{1}
}

func (x *GetParentsResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetParentsResponse) GetParents() map[uint64]int32 {
	if x != nil {
		return x.Parents
	}
	return nil
}

type GetDirStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *MetaContext           `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirStatRequest) Reset() {
	*x = GetDirStatRequest{}
	mi := &file_meta_directory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirStatRequest) ProtoMessage() {}

func (x *GetDirStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_directory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirStatRequest.ProtoReflect.Descriptor instead.
func (*GetDirStatRequest) Descriptor() ([]byte, []int) {
	return file_meta_directory_proto_rawDescGZIP(), []int{2}
}

func (x *GetDirStatRequest) GetCtx() *MetaContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *GetDirStatRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type GetDirStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         uint32                 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Space         int64                  `protobuf:"varint,3,opt,name=space,proto3" json:"space,omitempty"`
	Inodes        int64                  `protobuf:"varint,4,opt,name=inodes,proto3" json:"inodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirStatResponse) Reset() {
	*x = GetDirStatResponse{}
	mi := &file_meta_directory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirStatResponse) ProtoMessage() {}

func (x *GetDirStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_directory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirStatResponse.ProtoReflect.Descriptor instead.
func (*GetDirStatResponse) Descriptor() ([]byte, []int) {
	return file_meta_directory_proto_rawDescGZIP(), []int{3}
}

func (x *GetDirStatResponse) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetDirStatResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetDirStatResponse) GetSpace() int64 {
	if x != nil {
		return x.Space
	}
	return 0
}

func (x *GetDirStatResponse) GetInodes() int64 {
	if x != nil {
		return x.Inodes
	}
	return 0
}

var File_meta_directory_proto protoreflect.FileDescriptor

const file_meta_directory_proto_rawDesc = "" +
	"\n" +
	"\x14meta_directory.proto\x12\x04meta\x1a\x11meta_common.proto\"N\n" +
	"\x11GetParentsRequest\x12#\n" +
	"\x03ctx\x18\x01 \x01(\v2\x11.meta.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\"\xa7\x01\n" +
	"\x12GetParentsResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12?\n" +
	"\aparents\x18\x02 \x03(\v2%.meta.GetParentsResponse.ParentsEntryR\aparents\x1a:\n" +
	"\fParentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"N\n" +
	"\x11GetDirStatRequest\x12#\n" +
	"\x03ctx\x18\x01 \x01(\v2\x11.meta.MetaContextR\x03ctx\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\"p\n" +
	"\x12GetDirStatResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\rR\x05errno\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\x12\x14\n" +
	"\x05space\x18\x03 \x01(\x03R\x05space\x12\x16\n" +
	"\x06inodes\x18\x04 \x01(\x03R\x06inodesB,Z*github.com/juicedata/juicefs/pkg/meta/grpcb\x06proto3"

var (
	file_meta_directory_proto_rawDescOnce sync.Once
	file_meta_directory_proto_rawDescData []byte
)

func file_meta_directory_proto_rawDescGZIP() []byte {
	file_meta_directory_proto_rawDescOnce.Do(func() {
		file_meta_directory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_directory_proto_rawDesc), len(file_meta_directory_proto_rawDesc)))
	})
	return file_meta_directory_proto_rawDescData
}

var file_meta_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meta_directory_proto_goTypes = []any{
	(*GetParentsRequest)(nil),  // 0: meta.GetParentsRequest
	(*GetParentsResponse)(nil), // 1: meta.GetParentsResponse
	(*GetDirStatRequest)(nil),  // 2: meta.GetDirStatRequest
	(*GetDirStatResponse)(nil), // 3: meta.GetDirStatResponse
	nil,                        // 4: meta.GetParentsResponse.ParentsEntry
	(*MetaContext)(nil),        // 5: meta.MetaContext
}
var file_meta_directory_proto_depIdxs = []int32{
	5, // 0: meta.GetParentsRequest.ctx:type_name -> meta.MetaContext
	4, // 1: meta.GetParentsResponse.parents:type_name -> meta.GetParentsResponse.ParentsEntry
	5, // 2: meta.GetDirStatRequest.ctx:type_name -> meta.MetaContext
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_meta_directory_proto_init() }
func file_meta_directory_proto_init() {
	if File_meta_directory_proto != nil {
		return
	}
	file_meta_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_directory_proto_rawDesc), len(file_meta_directory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_directory_proto_goTypes,
		DependencyIndexes: file_meta_directory_proto_depIdxs,
		MessageInfos:      file_meta_directory_proto_msgTypes,
	}.Build()
	File_meta_directory_proto = out.File
	file_meta_directory_proto_goTypes = nil
	file_meta_directory_proto_depIdxs = nil
}
