// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/meta/authz_pb/authz.proto

package authz_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission levels matching auth.Permission
type Permission int32

const (
	Permission_PERMISSION_NONE Permission = 0
	Permission_PERMISSION_VIEW Permission = 1 // stat, lookup, readlink
	Permission_PERMISSION_READ Permission = 2 // open for read, read data
	Permission_PERMISSION_EDIT Permission = 3 // create, write, delete, rename
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "PERMISSION_NONE",
		1: "PERMISSION_VIEW",
		2: "PERMISSION_READ",
		3: "PERMISSION_EDIT",
	}
	Permission_value = map[string]int32{
		"PERMISSION_NONE": 0,
		"PERMISSION_VIEW": 1,
		"PERMISSION_READ": 2,
		"PERMISSION_EDIT": 3,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_meta_authz_pb_authz_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_pkg_meta_authz_pb_authz_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{0}
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                     // from OIDC token 'sub' claim
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                       // full filesystem path, e.g. "/company-abc/projects/render/out/frame.exr"
	Permission    Permission             `protobuf:"varint,3,opt,name=permission,proto3,enum=agio.renderfarm.authz.v1.Permission" json:"permission,omitempty"` // required permission level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CheckPermissionRequest) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_PERMISSION_NONE
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type CheckBulkPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                     // from OIDC token 'sub' claim
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`                                                     // up to 1000 paths per batch
	Permission    Permission             `protobuf:"varint,3,opt,name=permission,proto3,enum=agio.renderfarm.authz.v1.Permission" json:"permission,omitempty"` // same permission for all paths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBulkPermissionsRequest) Reset() {
	*x = CheckBulkPermissionsRequest{}
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkPermissionsRequest) ProtoMessage() {}

func (x *CheckBulkPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckBulkPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{2}
}

func (x *CheckBulkPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckBulkPermissionsRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *CheckBulkPermissionsRequest) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_PERMISSION_NONE
}

type CheckBulkPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       []bool                 `protobuf:"varint,1,rep,packed,name=allowed,proto3" json:"allowed,omitempty"` // same order as request paths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBulkPermissionsResponse) Reset() {
	*x = CheckBulkPermissionsResponse{}
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkPermissionsResponse) ProtoMessage() {}

func (x *CheckBulkPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckBulkPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CheckBulkPermissionsResponse) GetAllowed() []bool {
	if x != nil {
		return x.Allowed
	}
	return nil
}

type CheckOrganizationAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // from OIDC token 'sub' claim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOrganizationAdminRequest) Reset() {
	*x = CheckOrganizationAdminRequest{}
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOrganizationAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOrganizationAdminRequest) ProtoMessage() {}

func (x *CheckOrganizationAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOrganizationAdminRequest.ProtoReflect.Descriptor instead.
func (*CheckOrganizationAdminRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{4}
}

func (x *CheckOrganizationAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckOrganizationAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOrganizationAdminResponse) Reset() {
	*x = CheckOrganizationAdminResponse{}
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOrganizationAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOrganizationAdminResponse) ProtoMessage() {}

func (x *CheckOrganizationAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_authz_pb_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOrganizationAdminResponse.ProtoReflect.Descriptor instead.
func (*CheckOrganizationAdminResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_authz_pb_authz_proto_rawDescGZIP(), []int{5}
}

func (x *CheckOrganizationAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_pkg_meta_authz_pb_authz_proto protoreflect.FileDescriptor

const file_pkg_meta_authz_pb_authz_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/meta/authz_pb/authz.proto\x12\x18agio.renderfarm.authz.v1\"\x8b\x01\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12D\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2$.agio.renderfarm.authz.v1.PermissionR\n" +
	"permission\"3\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"\x92\x01\n" +
	"\x1bCheckBulkPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12D\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2$.agio.renderfarm.authz.v1.PermissionR\n" +
	"permission\"8\n" +
	"\x1cCheckBulkPermissionsResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x03(\bR\aallowed\"8\n" +
	"\x1dCheckOrganizationAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x1eCheckOrganizationAdminResponse\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin*`\n" +
	"\n" +
	"Permission\x12\x13\n" +
	"\x0fPERMISSION_NONE\x10\x00\x12\x13\n" +
	"\x0fPERMISSION_VIEW\x10\x01\x12\x13\n" +
	"\x0fPERMISSION_READ\x10\x02\x12\x13\n" +
	"\x0fPERMISSION_EDIT\x10\x032\x9c\x03\n" +
	"\fAuthzService\x12v\n" +
	"\x0fCheckPermission\x120.agio.renderfarm.authz.v1.CheckPermissionRequest\x1a1.agio.renderfarm.authz.v1.CheckPermissionResponse\x12\x85\x01\n" +
	"\x14CheckBulkPermissions\x125.agio.renderfarm.authz.v1.CheckBulkPermissionsRequest\x1a6.agio.renderfarm.authz.v1.CheckBulkPermissionsResponse\x12\x8b\x01\n" +
	"\x16CheckOrganizationAdmin\x127.agio.renderfarm.authz.v1.CheckOrganizationAdminRequest\x1a8.agio.renderfarm.authz.v1.CheckOrganizationAdminResponseB0Z.github.com/juicedata/juicefs/pkg/meta/authz_pbb\x06proto3"

var (
	file_pkg_meta_authz_pb_authz_proto_rawDescOnce sync.Once
	file_pkg_meta_authz_pb_authz_proto_rawDescData []byte
)

func file_pkg_meta_authz_pb_authz_proto_rawDescGZIP() []byte {
	file_pkg_meta_authz_pb_authz_proto_rawDescOnce.Do(func() {
		file_pkg_meta_authz_pb_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_meta_authz_pb_authz_proto_rawDesc), len(file_pkg_meta_authz_pb_authz_proto_rawDesc)))
	})
	return file_pkg_meta_authz_pb_authz_proto_rawDescData
}

var file_pkg_meta_authz_pb_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_meta_authz_pb_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_meta_authz_pb_authz_proto_goTypes = []any{
	(Permission)(0),                        // 0: agio.renderfarm.authz.v1.Permission
	(*CheckPermissionRequest)(nil),         // 1: agio.renderfarm.authz.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),        // 2: agio.renderfarm.authz.v1.CheckPermissionResponse
	(*CheckBulkPermissionsRequest)(nil),    // 3: agio.renderfarm.authz.v1.CheckBulkPermissionsRequest
	(*CheckBulkPermissionsResponse)(nil),   // 4: agio.renderfarm.authz.v1.CheckBulkPermissionsResponse
	(*CheckOrganizationAdminRequest)(nil),  // 5: agio.renderfarm.authz.v1.CheckOrganizationAdminRequest
	(*CheckOrganizationAdminResponse)(nil), // 6: agio.renderfarm.authz.v1.CheckOrganizationAdminResponse
}
var file_pkg_meta_authz_pb_authz_proto_depIdxs = []int32{
	0, // 0: agio.renderfarm.authz.v1.CheckPermissionRequest.permission:type_name -> agio.renderfarm.authz.v1.Permission
	0, // 1: agio.renderfarm.authz.v1.CheckBulkPermissionsRequest.permission:type_name -> agio.renderfarm.authz.v1.Permission
	1, // 2: agio.renderfarm.authz.v1.AuthzService.CheckPermission:input_type -> agio.renderfarm.authz.v1.CheckPermissionRequest
	3, // 3: agio.renderfarm.authz.v1.AuthzService.CheckBulkPermissions:input_type -> agio.renderfarm.authz.v1.CheckBulkPermissionsRequest
	5, // 4: agio.renderfarm.authz.v1.AuthzService.CheckOrganizationAdmin:input_type -> agio.renderfarm.authz.v1.CheckOrganizationAdminRequest
	2, // 5: agio.renderfarm.authz.v1.AuthzService.CheckPermission:output_type -> agio.renderfarm.authz.v1.CheckPermissionResponse
	4, // 6: agio.renderfarm.authz.v1.AuthzService.CheckBulkPermissions:output_type -> agio.renderfarm.authz.v1.CheckBulkPermissionsResponse
	6, // 7: agio.renderfarm.authz.v1.AuthzService.CheckOrganizationAdmin:output_type -> agio.renderfarm.authz.v1.CheckOrganizationAdminResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_meta_authz_pb_authz_proto_init() }
func file_pkg_meta_authz_pb_authz_proto_init() {
	if File_pkg_meta_authz_pb_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_meta_authz_pb_authz_proto_rawDesc), len(file_pkg_meta_authz_pb_authz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_meta_authz_pb_authz_proto_goTypes,
		DependencyIndexes: file_pkg_meta_authz_pb_authz_proto_depIdxs,
		EnumInfos:         file_pkg_meta_authz_pb_authz_proto_enumTypes,
		MessageInfos:      file_pkg_meta_authz_pb_authz_proto_msgTypes,
	}.Build()
	File_pkg_meta_authz_pb_authz_proto = out.File
	file_pkg_meta_authz_pb_authz_proto_goTypes = nil
	file_pkg_meta_authz_pb_authz_proto_depIdxs = nil
}
