//
// AGIO Renderfarm, Copyright 2026
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// NOTE: this file is a copy of agio-platform's
// src/application/authz/proto/key_manager.proto (sync with agio-platform).
// Keep the message/field layout identical; only go_package differs.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: key_manager.proto

package keymanager_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriveKeyManagerService_CreateFileKey_FullMethodName           = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/CreateFileKey"
	DriveKeyManagerService_GetFileFEK_FullMethodName              = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/GetFileFEK"
	DriveKeyManagerService_GetBulkFileFEK_FullMethodName          = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/GetBulkFileFEK"
	DriveKeyManagerService_FetchCompanyKEK_FullMethodName         = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/FetchCompanyKEK"
	DriveKeyManagerService_ProvisionCompanyKEK_FullMethodName     = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/ProvisionCompanyKEK"
	DriveKeyManagerService_GetPermissionGeneration_FullMethodName = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/GetPermissionGeneration"
	DriveKeyManagerService_GetSTSCredentials_FullMethodName       = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/GetSTSCredentials"
	DriveKeyManagerService_RotateFileFEK_FullMethodName           = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/RotateFileFEK"
	DriveKeyManagerService_RotateCompanyKEK_FullMethodName        = "/agio.platform.drive.crypto.v1.DriveKeyManagerService/RotateCompanyKEK"
)

// DriveKeyManagerServiceClient is the client API for DriveKeyManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DriveKeyManagerService manages the agio Drive encryption key hierarchy
// (Per-File FEK + Company KEK). It is served on the same gRPC server as
// AuthzService. Consumers: the JuiceFS Meta Proxy (user clients) and render nodes
// (FetchCompanyKEK only).
//
// Path contract: file-scoped RPCs (CreateFileKey, GetFileFEK, GetBulkFileFEK,
// RotateFileFEK) receive the FULL client path (e.g. "/company-abc/projects/file.exr")
// plus volume_name. The service strips the volume's companies prefix (the same
// mechanism AuthzService uses) and derives the company from the first remaining
// segment: the company code is resolved to a company ID server-side, so callers
// never send company_id for file-scoped operations. Company-scoped RPCs
// (FetchCompanyKEK, ProvisionCompanyKEK, RotateCompanyKEK) take company_id
// explicitly — their callers (render nodes, admins) know their own company.
type DriveKeyManagerServiceClient interface {
	// CreateFileKey generates a new 32-byte FEK for a file and returns it wrapped
	// under the company KEK as an AGFK blob. Requires Write permission on path.
	CreateFileKey(ctx context.Context, in *CreateFileKeyRequest, opts ...grpc.CallOption) (*CreateFileKeyResponse, error)
	// GetFileFEK unwraps a previously issued wrapped FEK and returns the plaintext
	// FEK (over TLS). Requires Read (read access) or Edit (write access) on path.
	GetFileFEK(ctx context.Context, in *GetFileFEKRequest, opts ...grpc.CallOption) (*GetFileFEKResponse, error)
	// GetBulkFileFEK unwraps up to 1000 wrapped FEKs in one call. Per-entry authz;
	// denied entries are reported individually, not as a whole-call failure.
	GetBulkFileFEK(ctx context.Context, in *GetBulkFileFEKRequest, opts ...grpc.CallOption) (*GetBulkFileFEKResponse, error)
	// FetchCompanyKEK returns the company KEK (wrapped under the KMS master key) for
	// a render node. Requires a valid Yandex Cloud IAM token (dedicated interceptor).
	FetchCompanyKEK(ctx context.Context, in *FetchCompanyKEKRequest, opts ...grpc.CallOption) (*FetchCompanyKEKResponse, error)
	// ProvisionCompanyKEK provisions the company KEK if not already present. Idempotent.
	ProvisionCompanyKEK(ctx context.Context, in *ProvisionCompanyKEKRequest, opts ...grpc.CallOption) (*ProvisionCompanyKEKResponse, error)
	// GetPermissionGeneration returns the current per-user permission generation
	// counter (0 when absent). Clients compare it on heartbeat to detect revocation.
	GetPermissionGeneration(ctx context.Context, in *GetPermissionGenerationRequest, opts ...grpc.CallOption) (*GetPermissionGenerationResponse, error)
	// GetSTSCredentials issues short-lived S3 credentials scoped to the company prefix.
	GetSTSCredentials(ctx context.Context, in *GetSTSCredentialsRequest, opts ...grpc.CallOption) (*GetSTSCredentialsResponse, error)
	// RotateFileFEK generates a new FEK version for an existing file. Requires an
	// organization admin (SpiceDB manage permission on the organization).
	RotateFileFEK(ctx context.Context, in *RotateFileFEKRequest, opts ...grpc.CallOption) (*RotateFileFEKResponse, error)
	// RotateCompanyKEK creates a new KEK version and retires the previous one.
	// Requires an organization admin.
	RotateCompanyKEK(ctx context.Context, in *RotateCompanyKEKRequest, opts ...grpc.CallOption) (*RotateCompanyKEKResponse, error)
}

type driveKeyManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriveKeyManagerServiceClient(cc grpc.ClientConnInterface) DriveKeyManagerServiceClient {
	return &driveKeyManagerServiceClient{cc}
}

func (c *driveKeyManagerServiceClient) CreateFileKey(ctx context.Context, in *CreateFileKeyRequest, opts ...grpc.CallOption) (*CreateFileKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileKeyResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_CreateFileKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) GetFileFEK(ctx context.Context, in *GetFileFEKRequest, opts ...grpc.CallOption) (*GetFileFEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileFEKResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_GetFileFEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) GetBulkFileFEK(ctx context.Context, in *GetBulkFileFEKRequest, opts ...grpc.CallOption) (*GetBulkFileFEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBulkFileFEKResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_GetBulkFileFEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) FetchCompanyKEK(ctx context.Context, in *FetchCompanyKEKRequest, opts ...grpc.CallOption) (*FetchCompanyKEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchCompanyKEKResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_FetchCompanyKEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) ProvisionCompanyKEK(ctx context.Context, in *ProvisionCompanyKEKRequest, opts ...grpc.CallOption) (*ProvisionCompanyKEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionCompanyKEKResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_ProvisionCompanyKEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) GetPermissionGeneration(ctx context.Context, in *GetPermissionGenerationRequest, opts ...grpc.CallOption) (*GetPermissionGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionGenerationResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_GetPermissionGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) GetSTSCredentials(ctx context.Context, in *GetSTSCredentialsRequest, opts ...grpc.CallOption) (*GetSTSCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSTSCredentialsResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_GetSTSCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) RotateFileFEK(ctx context.Context, in *RotateFileFEKRequest, opts ...grpc.CallOption) (*RotateFileFEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateFileFEKResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_RotateFileFEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveKeyManagerServiceClient) RotateCompanyKEK(ctx context.Context, in *RotateCompanyKEKRequest, opts ...grpc.CallOption) (*RotateCompanyKEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCompanyKEKResponse)
	err := c.cc.Invoke(ctx, DriveKeyManagerService_RotateCompanyKEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriveKeyManagerServiceServer is the server API for DriveKeyManagerService service.
// All implementations must embed UnimplementedDriveKeyManagerServiceServer
// for forward compatibility.
//
// DriveKeyManagerService manages the agio Drive encryption key hierarchy
// (Per-File FEK + Company KEK). It is served on the same gRPC server as
// AuthzService. Consumers: the JuiceFS Meta Proxy (user clients) and render nodes
// (FetchCompanyKEK only).
//
// Path contract: file-scoped RPCs (CreateFileKey, GetFileFEK, GetBulkFileFEK,
// RotateFileFEK) receive the FULL client path (e.g. "/company-abc/projects/file.exr")
// plus volume_name. The service strips the volume's companies prefix (the same
// mechanism AuthzService uses) and derives the company from the first remaining
// segment: the company code is resolved to a company ID server-side, so callers
// never send company_id for file-scoped operations. Company-scoped RPCs
// (FetchCompanyKEK, ProvisionCompanyKEK, RotateCompanyKEK) take company_id
// explicitly — their callers (render nodes, admins) know their own company.
type DriveKeyManagerServiceServer interface {
	// CreateFileKey generates a new 32-byte FEK for a file and returns it wrapped
	// under the company KEK as an AGFK blob. Requires Write permission on path.
	CreateFileKey(context.Context, *CreateFileKeyRequest) (*CreateFileKeyResponse, error)
	// GetFileFEK unwraps a previously issued wrapped FEK and returns the plaintext
	// FEK (over TLS). Requires Read (read access) or Edit (write access) on path.
	GetFileFEK(context.Context, *GetFileFEKRequest) (*GetFileFEKResponse, error)
	// GetBulkFileFEK unwraps up to 1000 wrapped FEKs in one call. Per-entry authz;
	// denied entries are reported individually, not as a whole-call failure.
	GetBulkFileFEK(context.Context, *GetBulkFileFEKRequest) (*GetBulkFileFEKResponse, error)
	// FetchCompanyKEK returns the company KEK (wrapped under the KMS master key) for
	// a render node. Requires a valid Yandex Cloud IAM token (dedicated interceptor).
	FetchCompanyKEK(context.Context, *FetchCompanyKEKRequest) (*FetchCompanyKEKResponse, error)
	// ProvisionCompanyKEK provisions the company KEK if not already present. Idempotent.
	ProvisionCompanyKEK(context.Context, *ProvisionCompanyKEKRequest) (*ProvisionCompanyKEKResponse, error)
	// GetPermissionGeneration returns the current per-user permission generation
	// counter (0 when absent). Clients compare it on heartbeat to detect revocation.
	GetPermissionGeneration(context.Context, *GetPermissionGenerationRequest) (*GetPermissionGenerationResponse, error)
	// GetSTSCredentials issues short-lived S3 credentials scoped to the company prefix.
	GetSTSCredentials(context.Context, *GetSTSCredentialsRequest) (*GetSTSCredentialsResponse, error)
	// RotateFileFEK generates a new FEK version for an existing file. Requires an
	// organization admin (SpiceDB manage permission on the organization).
	RotateFileFEK(context.Context, *RotateFileFEKRequest) (*RotateFileFEKResponse, error)
	// RotateCompanyKEK creates a new KEK version and retires the previous one.
	// Requires an organization admin.
	RotateCompanyKEK(context.Context, *RotateCompanyKEKRequest) (*RotateCompanyKEKResponse, error)
	mustEmbedUnimplementedDriveKeyManagerServiceServer()
}

// UnimplementedDriveKeyManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriveKeyManagerServiceServer struct{}

func (UnimplementedDriveKeyManagerServiceServer) CreateFileKey(context.Context, *CreateFileKeyRequest) (*CreateFileKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFileKey not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) GetFileFEK(context.Context, *GetFileFEKRequest) (*GetFileFEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileFEK not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) GetBulkFileFEK(context.Context, *GetBulkFileFEKRequest) (*GetBulkFileFEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBulkFileFEK not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) FetchCompanyKEK(context.Context, *FetchCompanyKEKRequest) (*FetchCompanyKEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCompanyKEK not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) ProvisionCompanyKEK(context.Context, *ProvisionCompanyKEKRequest) (*ProvisionCompanyKEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionCompanyKEK not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) GetPermissionGeneration(context.Context, *GetPermissionGenerationRequest) (*GetPermissionGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissionGeneration not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) GetSTSCredentials(context.Context, *GetSTSCredentialsRequest) (*GetSTSCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSTSCredentials not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) RotateFileFEK(context.Context, *RotateFileFEKRequest) (*RotateFileFEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateFileFEK not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) RotateCompanyKEK(context.Context, *RotateCompanyKEKRequest) (*RotateCompanyKEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCompanyKEK not implemented")
}
func (UnimplementedDriveKeyManagerServiceServer) mustEmbedUnimplementedDriveKeyManagerServiceServer() {
}
func (UnimplementedDriveKeyManagerServiceServer) testEmbeddedByValue() {}

// UnsafeDriveKeyManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriveKeyManagerServiceServer will
// result in compilation errors.
type UnsafeDriveKeyManagerServiceServer interface {
	mustEmbedUnimplementedDriveKeyManagerServiceServer()
}

func RegisterDriveKeyManagerServiceServer(s grpc.ServiceRegistrar, srv DriveKeyManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedDriveKeyManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriveKeyManagerService_ServiceDesc, srv)
}

func _DriveKeyManagerService_CreateFileKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).CreateFileKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_CreateFileKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).CreateFileKey(ctx, req.(*CreateFileKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_GetFileFEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileFEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).GetFileFEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_GetFileFEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).GetFileFEK(ctx, req.(*GetFileFEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_GetBulkFileFEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBulkFileFEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).GetBulkFileFEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_GetBulkFileFEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).GetBulkFileFEK(ctx, req.(*GetBulkFileFEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_FetchCompanyKEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCompanyKEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).FetchCompanyKEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_FetchCompanyKEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).FetchCompanyKEK(ctx, req.(*FetchCompanyKEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_ProvisionCompanyKEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionCompanyKEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).ProvisionCompanyKEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_ProvisionCompanyKEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).ProvisionCompanyKEK(ctx, req.(*ProvisionCompanyKEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_GetPermissionGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).GetPermissionGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_GetPermissionGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).GetPermissionGeneration(ctx, req.(*GetPermissionGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_GetSTSCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSTSCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).GetSTSCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_GetSTSCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).GetSTSCredentials(ctx, req.(*GetSTSCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_RotateFileFEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateFileFEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).RotateFileFEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_RotateFileFEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).RotateFileFEK(ctx, req.(*RotateFileFEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriveKeyManagerService_RotateCompanyKEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCompanyKEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveKeyManagerServiceServer).RotateCompanyKEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriveKeyManagerService_RotateCompanyKEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveKeyManagerServiceServer).RotateCompanyKEK(ctx, req.(*RotateCompanyKEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriveKeyManagerService_ServiceDesc is the grpc.ServiceDesc for DriveKeyManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriveKeyManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agio.platform.drive.crypto.v1.DriveKeyManagerService",
	HandlerType: (*DriveKeyManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileKey",
			Handler:    _DriveKeyManagerService_CreateFileKey_Handler,
		},
		{
			MethodName: "GetFileFEK",
			Handler:    _DriveKeyManagerService_GetFileFEK_Handler,
		},
		{
			MethodName: "GetBulkFileFEK",
			Handler:    _DriveKeyManagerService_GetBulkFileFEK_Handler,
		},
		{
			MethodName: "FetchCompanyKEK",
			Handler:    _DriveKeyManagerService_FetchCompanyKEK_Handler,
		},
		{
			MethodName: "ProvisionCompanyKEK",
			Handler:    _DriveKeyManagerService_ProvisionCompanyKEK_Handler,
		},
		{
			MethodName: "GetPermissionGeneration",
			Handler:    _DriveKeyManagerService_GetPermissionGeneration_Handler,
		},
		{
			MethodName: "GetSTSCredentials",
			Handler:    _DriveKeyManagerService_GetSTSCredentials_Handler,
		},
		{
			MethodName: "RotateFileFEK",
			Handler:    _DriveKeyManagerService_RotateFileFEK_Handler,
		},
		{
			MethodName: "RotateCompanyKEK",
			Handler:    _DriveKeyManagerService_RotateCompanyKEK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "key_manager.proto",
}
