//
// AGIO Renderfarm, Copyright 2026
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// NOTE: this file is a copy of agio-platform's
// src/application/authz/proto/key_manager.proto (sync with agio-platform).
// Keep the message/field layout identical; only go_package differs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: key_manager.proto

package keymanager_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateFileKeyRequest carries the file identity and the AAD components needed to
// wrap the FEK. The AAD is volume_uuid || company_id || drive_file_id || inode ||
// fek_version (byte encoding pinned by cross-repo known-answer vectors).
//
// The company is NOT carried by the caller: the client mounts the whole facility
// and sees companies per authz, so it cannot name a company at mount time. The
// service derives it from the first path segment after stripping the volume's
// companies prefix (see the Path contract on DriveKeyManagerService).
type CreateFileKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // from OIDC token 'sub' claim (UUID)
	VolumeUuid    string                 `protobuf:"bytes,3,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`      // JuiceFS volume UUID (AAD component)
	DriveFileId   string                 `protobuf:"bytes,4,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"` // stable file identifier (AAD component)
	Inode         int64                  `protobuf:"varint,5,opt,name=inode,proto3" json:"inode,omitempty"`                                 // inode number (AAD component)
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                                    // full client path, e.g. /company-abc/projects/file.exr
	VolumeName    string                 `protobuf:"bytes,7,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`      // JuiceFS volume name — resolves the companies prefix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileKeyRequest) Reset() {
	*x = CreateFileKeyRequest{}
	mi := &file_key_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileKeyRequest) ProtoMessage() {}

func (x *CreateFileKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateFileKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateFileKeyRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *CreateFileKeyRequest) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *CreateFileKeyRequest) GetInode() int64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *CreateFileKeyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileKeyRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type CreateFileKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrappedFek    []byte                 `protobuf:"bytes,1,opt,name=wrapped_fek,json=wrappedFek,proto3" json:"wrapped_fek,omitempty"` // AGFK blob
	DriveFileId   string                 `protobuf:"bytes,2,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	FekVersion    uint32                 `protobuf:"varint,3,opt,name=fek_version,json=fekVersion,proto3" json:"fek_version,omitempty"` // always 1 on create
	KekVersion    uint32                 `protobuf:"varint,4,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"` // Company KEK version used to wrap
	CryptoAlg     string                 `protobuf:"bytes,5,opt,name=crypto_alg,json=cryptoAlg,proto3" json:"crypto_alg,omitempty"`     // "AES-256-GCM"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileKeyResponse) Reset() {
	*x = CreateFileKeyResponse{}
	mi := &file_key_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileKeyResponse) ProtoMessage() {}

func (x *CreateFileKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateFileKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileKeyResponse) GetWrappedFek() []byte {
	if x != nil {
		return x.WrappedFek
	}
	return nil
}

func (x *CreateFileKeyResponse) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *CreateFileKeyResponse) GetFekVersion() uint32 {
	if x != nil {
		return x.FekVersion
	}
	return 0
}

func (x *CreateFileKeyResponse) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *CreateFileKeyResponse) GetCryptoAlg() string {
	if x != nil {
		return x.CryptoAlg
	}
	return ""
}

// GetFileFEKRequest carries the wrapped FEK (issued by CreateFileKey) plus the AAD
// components so the service can reconstruct the AAD and unwrap it. The company is
// derived server-side from the path (see CreateFileKeyRequest).
type GetFileFEKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VolumeUuid    string                 `protobuf:"bytes,3,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	DriveFileId   string                 `protobuf:"bytes,4,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	Inode         int64                  `protobuf:"varint,5,opt,name=inode,proto3" json:"inode,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                                   // full client path, e.g. /company-abc/projects/file.exr
	WrappedFek    []byte                 `protobuf:"bytes,7,opt,name=wrapped_fek,json=wrappedFek,proto3" json:"wrapped_fek,omitempty"`     // AGFK blob to unwrap
	WriteAccess   bool                   `protobuf:"varint,8,opt,name=write_access,json=writeAccess,proto3" json:"write_access,omitempty"` // true -> requires Edit, false -> Read
	FekVersion    uint32                 `protobuf:"varint,9,opt,name=fek_version,json=fekVersion,proto3" json:"fek_version,omitempty"`    // FEK version (AAD component; from CreateFileKey)
	VolumeName    string                 `protobuf:"bytes,10,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`    // JuiceFS volume name — resolves the companies prefix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileFEKRequest) Reset() {
	*x = GetFileFEKRequest{}
	mi := &file_key_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileFEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileFEKRequest) ProtoMessage() {}

func (x *GetFileFEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileFEKRequest.ProtoReflect.Descriptor instead.
func (*GetFileFEKRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileFEKRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFileFEKRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *GetFileFEKRequest) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *GetFileFEKRequest) GetInode() int64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *GetFileFEKRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileFEKRequest) GetWrappedFek() []byte {
	if x != nil {
		return x.WrappedFek
	}
	return nil
}

func (x *GetFileFEKRequest) GetWriteAccess() bool {
	if x != nil {
		return x.WriteAccess
	}
	return false
}

func (x *GetFileFEKRequest) GetFekVersion() uint32 {
	if x != nil {
		return x.FekVersion
	}
	return 0
}

func (x *GetFileFEKRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type GetFileFEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fek           []byte                 `protobuf:"bytes,1,opt,name=fek,proto3" json:"fek,omitempty"` // plaintext FEK (32 bytes), valid over TLS only
	DriveFileId   string                 `protobuf:"bytes,2,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	FekVersion    uint32                 `protobuf:"varint,3,opt,name=fek_version,json=fekVersion,proto3" json:"fek_version,omitempty"`
	KekVersion    uint32                 `protobuf:"varint,4,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	CryptoAlg     string                 `protobuf:"bytes,5,opt,name=crypto_alg,json=cryptoAlg,proto3" json:"crypto_alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileFEKResponse) Reset() {
	*x = GetFileFEKResponse{}
	mi := &file_key_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileFEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileFEKResponse) ProtoMessage() {}

func (x *GetFileFEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileFEKResponse.ProtoReflect.Descriptor instead.
func (*GetFileFEKResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileFEKResponse) GetFek() []byte {
	if x != nil {
		return x.Fek
	}
	return nil
}

func (x *GetFileFEKResponse) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *GetFileFEKResponse) GetFekVersion() uint32 {
	if x != nil {
		return x.FekVersion
	}
	return 0
}

func (x *GetFileFEKResponse) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *GetFileFEKResponse) GetCryptoAlg() string {
	if x != nil {
		return x.CryptoAlg
	}
	return ""
}

// FileFEKEntry is one entry of a GetBulkFileFEK batch.
type FileFEKEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveFileId   string                 `protobuf:"bytes,1,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	Inode         int64                  `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	WrappedFek    []byte                 `protobuf:"bytes,4,opt,name=wrapped_fek,json=wrappedFek,proto3" json:"wrapped_fek,omitempty"`
	WriteAccess   bool                   `protobuf:"varint,5,opt,name=write_access,json=writeAccess,proto3" json:"write_access,omitempty"`
	FekVersion    uint32                 `protobuf:"varint,6,opt,name=fek_version,json=fekVersion,proto3" json:"fek_version,omitempty"` // FEK version (AAD component)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileFEKEntry) Reset() {
	*x = FileFEKEntry{}
	mi := &file_key_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileFEKEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFEKEntry) ProtoMessage() {}

func (x *FileFEKEntry) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFEKEntry.ProtoReflect.Descriptor instead.
func (*FileFEKEntry) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{4}
}

func (x *FileFEKEntry) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *FileFEKEntry) GetInode() int64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FileFEKEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileFEKEntry) GetWrappedFek() []byte {
	if x != nil {
		return x.WrappedFek
	}
	return nil
}

func (x *FileFEKEntry) GetWriteAccess() bool {
	if x != nil {
		return x.WriteAccess
	}
	return false
}

func (x *FileFEKEntry) GetFekVersion() uint32 {
	if x != nil {
		return x.FekVersion
	}
	return 0
}

// GetBulkFileFEKRequest: the company is derived server-side per entry from its path
// (entries of one batch may belong to different companies).
type GetBulkFileFEKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VolumeUuid    string                 `protobuf:"bytes,3,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	Entries       []*FileFEKEntry        `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`                         // up to 1000
	VolumeName    string                 `protobuf:"bytes,5,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"` // JuiceFS volume name — resolves the companies prefix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkFileFEKRequest) Reset() {
	*x = GetBulkFileFEKRequest{}
	mi := &file_key_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkFileFEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkFileFEKRequest) ProtoMessage() {}

func (x *GetBulkFileFEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkFileFEKRequest.ProtoReflect.Descriptor instead.
func (*GetBulkFileFEKRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{5}
}

func (x *GetBulkFileFEKRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBulkFileFEKRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *GetBulkFileFEKRequest) GetEntries() []*FileFEKEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetBulkFileFEKRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

// FileFEKResult is the per-entry outcome of a GetBulkFileFEK batch. When allowed is
// false, fek is empty and error carries the reason (e.g. "permission denied").
type FileFEKResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveFileId   string                 `protobuf:"bytes,1,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	Fek           []byte                 `protobuf:"bytes,2,opt,name=fek,proto3" json:"fek,omitempty"`
	FekVersion    uint32                 `protobuf:"varint,3,opt,name=fek_version,json=fekVersion,proto3" json:"fek_version,omitempty"`
	KekVersion    uint32                 `protobuf:"varint,4,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	CryptoAlg     string                 `protobuf:"bytes,5,opt,name=crypto_alg,json=cryptoAlg,proto3" json:"crypto_alg,omitempty"`
	Allowed       bool                   `protobuf:"varint,6,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileFEKResult) Reset() {
	*x = FileFEKResult{}
	mi := &file_key_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileFEKResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFEKResult) ProtoMessage() {}

func (x *FileFEKResult) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFEKResult.ProtoReflect.Descriptor instead.
func (*FileFEKResult) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{6}
}

func (x *FileFEKResult) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *FileFEKResult) GetFek() []byte {
	if x != nil {
		return x.Fek
	}
	return nil
}

func (x *FileFEKResult) GetFekVersion() uint32 {
	if x != nil {
		return x.FekVersion
	}
	return 0
}

func (x *FileFEKResult) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *FileFEKResult) GetCryptoAlg() string {
	if x != nil {
		return x.CryptoAlg
	}
	return ""
}

func (x *FileFEKResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *FileFEKResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBulkFileFEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FileFEKResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // same order as request entries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkFileFEKResponse) Reset() {
	*x = GetBulkFileFEKResponse{}
	mi := &file_key_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkFileFEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkFileFEKResponse) ProtoMessage() {}

func (x *GetBulkFileFEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkFileFEKResponse.ProtoReflect.Descriptor instead.
func (*GetBulkFileFEKResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{7}
}

func (x *GetBulkFileFEKResponse) GetResults() []*FileFEKResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// FetchCompanyKEKRequest identifies the calling render node. The YC IAM token is
// carried in the gRPC metadata and verified by the interceptor, not here.
type FetchCompanyKEKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // render node identity (from the verified IAM token)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCompanyKEKRequest) Reset() {
	*x = FetchCompanyKEKRequest{}
	mi := &file_key_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCompanyKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCompanyKEKRequest) ProtoMessage() {}

func (x *FetchCompanyKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCompanyKEKRequest.ProtoReflect.Descriptor instead.
func (*FetchCompanyKEKRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{8}
}

func (x *FetchCompanyKEKRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *FetchCompanyKEKRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// FetchCompanyKEKResponse carries the plaintext Company KEK (over TLS) so the render
// node can unwrap FEKs locally. The node holds it in RAM for the mount session only.
type FetchCompanyKEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kek           []byte                 `protobuf:"bytes,1,opt,name=kek,proto3" json:"kek,omitempty"` // plaintext Company KEK (32 bytes)
	KekVersion    uint32                 `protobuf:"varint,2,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCompanyKEKResponse) Reset() {
	*x = FetchCompanyKEKResponse{}
	mi := &file_key_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCompanyKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCompanyKEKResponse) ProtoMessage() {}

func (x *FetchCompanyKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCompanyKEKResponse.ProtoReflect.Descriptor instead.
func (*FetchCompanyKEKResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{9}
}

func (x *FetchCompanyKEKResponse) GetKek() []byte {
	if x != nil {
		return x.Kek
	}
	return nil
}

func (x *FetchCompanyKEKResponse) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

type ProvisionCompanyKEKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCompanyKEKRequest) Reset() {
	*x = ProvisionCompanyKEKRequest{}
	mi := &file_key_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCompanyKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCompanyKEKRequest) ProtoMessage() {}

func (x *ProvisionCompanyKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCompanyKEKRequest.ProtoReflect.Descriptor instead.
func (*ProvisionCompanyKEKRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{10}
}

func (x *ProvisionCompanyKEKRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ProvisionCompanyKEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KekVersion    uint32                 `protobuf:"varint,1,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // false when the KEK already existed (idempotent no-op)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCompanyKEKResponse) Reset() {
	*x = ProvisionCompanyKEKResponse{}
	mi := &file_key_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCompanyKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCompanyKEKResponse) ProtoMessage() {}

func (x *ProvisionCompanyKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCompanyKEKResponse.ProtoReflect.Descriptor instead.
func (*ProvisionCompanyKEKResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{11}
}

func (x *ProvisionCompanyKEKResponse) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *ProvisionCompanyKEKResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetPermissionGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionGenerationRequest) Reset() {
	*x = GetPermissionGenerationRequest{}
	mi := &file_key_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionGenerationRequest) ProtoMessage() {}

func (x *GetPermissionGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionGenerationRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionGenerationRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{12}
}

func (x *GetPermissionGenerationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPermissionGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"` // 0 when the counter is absent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionGenerationResponse) Reset() {
	*x = GetPermissionGenerationResponse{}
	mi := &file_key_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionGenerationResponse) ProtoMessage() {}

func (x *GetPermissionGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionGenerationResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionGenerationResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{13}
}

func (x *GetPermissionGenerationResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type GetSTSCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSTSCredentialsRequest) Reset() {
	*x = GetSTSCredentialsRequest{}
	mi := &file_key_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSTSCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSTSCredentialsRequest) ProtoMessage() {}

func (x *GetSTSCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSTSCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetSTSCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{14}
}

func (x *GetSTSCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSTSCredentialsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// GetSTSCredentialsResponse carries short-lived S3 credentials (TTL <= 60 min). They
// are never persisted; each issuance is audited.
type GetSTSCredentialsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpirationUnix  int64                  `protobuf:"varint,4,opt,name=expiration_unix,json=expirationUnix,proto3" json:"expiration_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSTSCredentialsResponse) Reset() {
	*x = GetSTSCredentialsResponse{}
	mi := &file_key_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSTSCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSTSCredentialsResponse) ProtoMessage() {}

func (x *GetSTSCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSTSCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetSTSCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{15}
}

func (x *GetSTSCredentialsResponse) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *GetSTSCredentialsResponse) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *GetSTSCredentialsResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GetSTSCredentialsResponse) GetExpirationUnix() int64 {
	if x != nil {
		return x.ExpirationUnix
	}
	return 0
}

// RotateFileFEKRequest: the company is derived server-side from the path (the caller
// is an org admin acting on a file, not on a company).
type RotateFileFEKRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VolumeUuid        string                 `protobuf:"bytes,3,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	DriveFileId       string                 `protobuf:"bytes,4,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	Inode             int64                  `protobuf:"varint,5,opt,name=inode,proto3" json:"inode,omitempty"`
	Path              string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                                                       // full client path, e.g. /company-abc/projects/file.exr
	CurrentFekVersion uint32                 `protobuf:"varint,7,opt,name=current_fek_version,json=currentFekVersion,proto3" json:"current_fek_version,omitempty"` // FEK version in effect before rotation (>= 1)
	VolumeName        string                 `protobuf:"bytes,8,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`                         // JuiceFS volume name — resolves the companies prefix
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RotateFileFEKRequest) Reset() {
	*x = RotateFileFEKRequest{}
	mi := &file_key_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateFileFEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateFileFEKRequest) ProtoMessage() {}

func (x *RotateFileFEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateFileFEKRequest.ProtoReflect.Descriptor instead.
func (*RotateFileFEKRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{16}
}

func (x *RotateFileFEKRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RotateFileFEKRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *RotateFileFEKRequest) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *RotateFileFEKRequest) GetInode() int64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *RotateFileFEKRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RotateFileFEKRequest) GetCurrentFekVersion() uint32 {
	if x != nil {
		return x.CurrentFekVersion
	}
	return 0
}

func (x *RotateFileFEKRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type RotateFileFEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrappedFek    []byte                 `protobuf:"bytes,1,opt,name=wrapped_fek,json=wrappedFek,proto3" json:"wrapped_fek,omitempty"`  // new AGFK under the current KEK
	FekVersion    uint32                 `protobuf:"varint,2,opt,name=fek_version,json=fekVersion,proto3" json:"fek_version,omitempty"` // previous + 1
	KekVersion    uint32                 `protobuf:"varint,3,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	CryptoAlg     string                 `protobuf:"bytes,4,opt,name=crypto_alg,json=cryptoAlg,proto3" json:"crypto_alg,omitempty"`
	PlaintextFek  []byte                 `protobuf:"bytes,5,opt,name=plaintext_fek,json=plaintextFek,proto3" json:"plaintext_fek,omitempty"` // new FEK (over TLS only); the proxy needs it to re-wrap slices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateFileFEKResponse) Reset() {
	*x = RotateFileFEKResponse{}
	mi := &file_key_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateFileFEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateFileFEKResponse) ProtoMessage() {}

func (x *RotateFileFEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateFileFEKResponse.ProtoReflect.Descriptor instead.
func (*RotateFileFEKResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{17}
}

func (x *RotateFileFEKResponse) GetWrappedFek() []byte {
	if x != nil {
		return x.WrappedFek
	}
	return nil
}

func (x *RotateFileFEKResponse) GetFekVersion() uint32 {
	if x != nil {
		return x.FekVersion
	}
	return 0
}

func (x *RotateFileFEKResponse) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *RotateFileFEKResponse) GetCryptoAlg() string {
	if x != nil {
		return x.CryptoAlg
	}
	return ""
}

func (x *RotateFileFEKResponse) GetPlaintextFek() []byte {
	if x != nil {
		return x.PlaintextFek
	}
	return nil
}

type RotateCompanyKEKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // org admin performing the rotation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCompanyKEKRequest) Reset() {
	*x = RotateCompanyKEKRequest{}
	mi := &file_key_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCompanyKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCompanyKEKRequest) ProtoMessage() {}

func (x *RotateCompanyKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCompanyKEKRequest.ProtoReflect.Descriptor instead.
func (*RotateCompanyKEKRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{18}
}

func (x *RotateCompanyKEKRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *RotateCompanyKEKRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RotateCompanyKEKResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NewKekVersion      uint32                 `protobuf:"varint,1,opt,name=new_kek_version,json=newKekVersion,proto3" json:"new_kek_version,omitempty"`
	RetiringKekVersion uint32                 `protobuf:"varint,2,opt,name=retiring_kek_version,json=retiringKekVersion,proto3" json:"retiring_kek_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RotateCompanyKEKResponse) Reset() {
	*x = RotateCompanyKEKResponse{}
	mi := &file_key_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCompanyKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCompanyKEKResponse) ProtoMessage() {}

func (x *RotateCompanyKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCompanyKEKResponse.ProtoReflect.Descriptor instead.
func (*RotateCompanyKEKResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{19}
}

func (x *RotateCompanyKEKResponse) GetNewKekVersion() uint32 {
	if x != nil {
		return x.NewKekVersion
	}
	return 0
}

func (x *RotateCompanyKEKResponse) GetRetiringKekVersion() uint32 {
	if x != nil {
		return x.RetiringKekVersion
	}
	return 0
}

var File_key_manager_proto protoreflect.FileDescriptor

const file_key_manager_proto_rawDesc = "" +
	"\n" +
	"\x11key_manager.proto\x12\x1dagio.platform.drive.crypto.v1\"\xc5\x01\n" +
	"\x14CreateFileKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vvolume_uuid\x18\x03 \x01(\tR\n" +
	"volumeUuid\x12\"\n" +
	"\rdrive_file_id\x18\x04 \x01(\tR\vdriveFileId\x12\x14\n" +
	"\x05inode\x18\x05 \x01(\x03R\x05inode\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1f\n" +
	"\vvolume_name\x18\a \x01(\tR\n" +
	"volumeNameJ\x04\b\x02\x10\x03\"\xbd\x01\n" +
	"\x15CreateFileKeyResponse\x12\x1f\n" +
	"\vwrapped_fek\x18\x01 \x01(\fR\n" +
	"wrappedFek\x12\"\n" +
	"\rdrive_file_id\x18\x02 \x01(\tR\vdriveFileId\x12\x1f\n" +
	"\vfek_version\x18\x03 \x01(\rR\n" +
	"fekVersion\x12\x1f\n" +
	"\vkek_version\x18\x04 \x01(\rR\n" +
	"kekVersion\x12\x1d\n" +
	"\n" +
	"crypto_alg\x18\x05 \x01(\tR\tcryptoAlg\"\xa7\x02\n" +
	"\x11GetFileFEKRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vvolume_uuid\x18\x03 \x01(\tR\n" +
	"volumeUuid\x12\"\n" +
	"\rdrive_file_id\x18\x04 \x01(\tR\vdriveFileId\x12\x14\n" +
	"\x05inode\x18\x05 \x01(\x03R\x05inode\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1f\n" +
	"\vwrapped_fek\x18\a \x01(\fR\n" +
	"wrappedFek\x12!\n" +
	"\fwrite_access\x18\b \x01(\bR\vwriteAccess\x12\x1f\n" +
	"\vfek_version\x18\t \x01(\rR\n" +
	"fekVersion\x12\x1f\n" +
	"\vvolume_name\x18\n" +
	" \x01(\tR\n" +
	"volumeNameJ\x04\b\x02\x10\x03\"\xab\x01\n" +
	"\x12GetFileFEKResponse\x12\x10\n" +
	"\x03fek\x18\x01 \x01(\fR\x03fek\x12\"\n" +
	"\rdrive_file_id\x18\x02 \x01(\tR\vdriveFileId\x12\x1f\n" +
	"\vfek_version\x18\x03 \x01(\rR\n" +
	"fekVersion\x12\x1f\n" +
	"\vkek_version\x18\x04 \x01(\rR\n" +
	"kekVersion\x12\x1d\n" +
	"\n" +
	"crypto_alg\x18\x05 \x01(\tR\tcryptoAlg\"\xc1\x01\n" +
	"\fFileFEKEntry\x12\"\n" +
	"\rdrive_file_id\x18\x01 \x01(\tR\vdriveFileId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x03R\x05inode\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vwrapped_fek\x18\x04 \x01(\fR\n" +
	"wrappedFek\x12!\n" +
	"\fwrite_access\x18\x05 \x01(\bR\vwriteAccess\x12\x1f\n" +
	"\vfek_version\x18\x06 \x01(\rR\n" +
	"fekVersion\"\xbf\x01\n" +
	"\x15GetBulkFileFEKRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vvolume_uuid\x18\x03 \x01(\tR\n" +
	"volumeUuid\x12E\n" +
	"\aentries\x18\x04 \x03(\v2+.agio.platform.drive.crypto.v1.FileFEKEntryR\aentries\x12\x1f\n" +
	"\vvolume_name\x18\x05 \x01(\tR\n" +
	"volumeNameJ\x04\b\x02\x10\x03\"\xd6\x01\n" +
	"\rFileFEKResult\x12\"\n" +
	"\rdrive_file_id\x18\x01 \x01(\tR\vdriveFileId\x12\x10\n" +
	"\x03fek\x18\x02 \x01(\fR\x03fek\x12\x1f\n" +
	"\vfek_version\x18\x03 \x01(\rR\n" +
	"fekVersion\x12\x1f\n" +
	"\vkek_version\x18\x04 \x01(\rR\n" +
	"kekVersion\x12\x1d\n" +
	"\n" +
	"crypto_alg\x18\x05 \x01(\tR\tcryptoAlg\x12\x18\n" +
	"\aallowed\x18\x06 \x01(\bR\aallowed\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"`\n" +
	"\x16GetBulkFileFEKResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.agio.platform.drive.crypto.v1.FileFEKResultR\aresults\"P\n" +
	"\x16FetchCompanyKEKRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"L\n" +
	"\x17FetchCompanyKEKResponse\x12\x10\n" +
	"\x03kek\x18\x01 \x01(\fR\x03kek\x12\x1f\n" +
	"\vkek_version\x18\x02 \x01(\rR\n" +
	"kekVersion\";\n" +
	"\x1aProvisionCompanyKEKRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"X\n" +
	"\x1bProvisionCompanyKEKResponse\x12\x1f\n" +
	"\vkek_version\x18\x01 \x01(\rR\n" +
	"kekVersion\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"9\n" +
	"\x1eGetPermissionGenerationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x1fGetPermissionGenerationResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\"R\n" +
	"\x18GetSTSCredentialsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"\xb9\x01\n" +
	"\x19GetSTSCredentialsResponse\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12'\n" +
	"\x0fexpiration_unix\x18\x04 \x01(\x03R\x0eexpirationUnix\"\xf5\x01\n" +
	"\x14RotateFileFEKRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vvolume_uuid\x18\x03 \x01(\tR\n" +
	"volumeUuid\x12\"\n" +
	"\rdrive_file_id\x18\x04 \x01(\tR\vdriveFileId\x12\x14\n" +
	"\x05inode\x18\x05 \x01(\x03R\x05inode\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12.\n" +
	"\x13current_fek_version\x18\a \x01(\rR\x11currentFekVersion\x12\x1f\n" +
	"\vvolume_name\x18\b \x01(\tR\n" +
	"volumeNameJ\x04\b\x02\x10\x03\"\xbe\x01\n" +
	"\x15RotateFileFEKResponse\x12\x1f\n" +
	"\vwrapped_fek\x18\x01 \x01(\fR\n" +
	"wrappedFek\x12\x1f\n" +
	"\vfek_version\x18\x02 \x01(\rR\n" +
	"fekVersion\x12\x1f\n" +
	"\vkek_version\x18\x03 \x01(\rR\n" +
	"kekVersion\x12\x1d\n" +
	"\n" +
	"crypto_alg\x18\x04 \x01(\tR\tcryptoAlg\x12#\n" +
	"\rplaintext_fek\x18\x05 \x01(\fR\fplaintextFek\"Q\n" +
	"\x17RotateCompanyKEKRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"t\n" +
	"\x18RotateCompanyKEKResponse\x12&\n" +
	"\x0fnew_kek_version\x18\x01 \x01(\rR\rnewKekVersion\x120\n" +
	"\x14retiring_kek_version\x18\x02 \x01(\rR\x12retiringKekVersion2\xbe\t\n" +
	"\x16DriveKeyManagerService\x12z\n" +
	"\rCreateFileKey\x123.agio.platform.drive.crypto.v1.CreateFileKeyRequest\x1a4.agio.platform.drive.crypto.v1.CreateFileKeyResponse\x12q\n" +
	"\n" +
	"GetFileFEK\x120.agio.platform.drive.crypto.v1.GetFileFEKRequest\x1a1.agio.platform.drive.crypto.v1.GetFileFEKResponse\x12}\n" +
	"\x0eGetBulkFileFEK\x124.agio.platform.drive.crypto.v1.GetBulkFileFEKRequest\x1a5.agio.platform.drive.crypto.v1.GetBulkFileFEKResponse\x12\x80\x01\n" +
	"\x0fFetchCompanyKEK\x125.agio.platform.drive.crypto.v1.FetchCompanyKEKRequest\x1a6.agio.platform.drive.crypto.v1.FetchCompanyKEKResponse\x12\x8c\x01\n" +
	"\x13ProvisionCompanyKEK\x129.agio.platform.drive.crypto.v1.ProvisionCompanyKEKRequest\x1a:.agio.platform.drive.crypto.v1.ProvisionCompanyKEKResponse\x12\x98\x01\n" +
	"\x17GetPermissionGeneration\x12=.agio.platform.drive.crypto.v1.GetPermissionGenerationRequest\x1a>.agio.platform.drive.crypto.v1.GetPermissionGenerationResponse\x12\x86\x01\n" +
	"\x11GetSTSCredentials\x127.agio.platform.drive.crypto.v1.GetSTSCredentialsRequest\x1a8.agio.platform.drive.crypto.v1.GetSTSCredentialsResponse\x12z\n" +
	"\rRotateFileFEK\x123.agio.platform.drive.crypto.v1.RotateFileFEKRequest\x1a4.agio.platform.drive.crypto.v1.RotateFileFEKResponse\x12\x83\x01\n" +
	"\x10RotateCompanyKEK\x126.agio.platform.drive.crypto.v1.RotateCompanyKEKRequest\x1a7.agio.platform.drive.crypto.v1.RotateCompanyKEKResponseB5Z3github.com/juicedata/juicefs/pkg/meta/keymanager_pbb\x06proto3"

var (
	file_key_manager_proto_rawDescOnce sync.Once
	file_key_manager_proto_rawDescData []byte
)

func file_key_manager_proto_rawDescGZIP() []byte {
	file_key_manager_proto_rawDescOnce.Do(func() {
		file_key_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_manager_proto_rawDesc), len(file_key_manager_proto_rawDesc)))
	})
	return file_key_manager_proto_rawDescData
}

var file_key_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_key_manager_proto_goTypes = []any{
	(*CreateFileKeyRequest)(nil),            // 0: agio.platform.drive.crypto.v1.CreateFileKeyRequest
	(*CreateFileKeyResponse)(nil),           // 1: agio.platform.drive.crypto.v1.CreateFileKeyResponse
	(*GetFileFEKRequest)(nil),               // 2: agio.platform.drive.crypto.v1.GetFileFEKRequest
	(*GetFileFEKResponse)(nil),              // 3: agio.platform.drive.crypto.v1.GetFileFEKResponse
	(*FileFEKEntry)(nil),                    // 4: agio.platform.drive.crypto.v1.FileFEKEntry
	(*GetBulkFileFEKRequest)(nil),           // 5: agio.platform.drive.crypto.v1.GetBulkFileFEKRequest
	(*FileFEKResult)(nil),                   // 6: agio.platform.drive.crypto.v1.FileFEKResult
	(*GetBulkFileFEKResponse)(nil),          // 7: agio.platform.drive.crypto.v1.GetBulkFileFEKResponse
	(*FetchCompanyKEKRequest)(nil),          // 8: agio.platform.drive.crypto.v1.FetchCompanyKEKRequest
	(*FetchCompanyKEKResponse)(nil),         // 9: agio.platform.drive.crypto.v1.FetchCompanyKEKResponse
	(*ProvisionCompanyKEKRequest)(nil),      // 10: agio.platform.drive.crypto.v1.ProvisionCompanyKEKRequest
	(*ProvisionCompanyKEKResponse)(nil),     // 11: agio.platform.drive.crypto.v1.ProvisionCompanyKEKResponse
	(*GetPermissionGenerationRequest)(nil),  // 12: agio.platform.drive.crypto.v1.GetPermissionGenerationRequest
	(*GetPermissionGenerationResponse)(nil), // 13: agio.platform.drive.crypto.v1.GetPermissionGenerationResponse
	(*GetSTSCredentialsRequest)(nil),        // 14: agio.platform.drive.crypto.v1.GetSTSCredentialsRequest
	(*GetSTSCredentialsResponse)(nil),       // 15: agio.platform.drive.crypto.v1.GetSTSCredentialsResponse
	(*RotateFileFEKRequest)(nil),            // 16: agio.platform.drive.crypto.v1.RotateFileFEKRequest
	(*RotateFileFEKResponse)(nil),           // 17: agio.platform.drive.crypto.v1.RotateFileFEKResponse
	(*RotateCompanyKEKRequest)(nil),         // 18: agio.platform.drive.crypto.v1.RotateCompanyKEKRequest
	(*RotateCompanyKEKResponse)(nil),        // 19: agio.platform.drive.crypto.v1.RotateCompanyKEKResponse
}
var file_key_manager_proto_depIdxs = []int32{
	4,  // 0: agio.platform.drive.crypto.v1.GetBulkFileFEKRequest.entries:type_name -> agio.platform.drive.crypto.v1.FileFEKEntry
	6,  // 1: agio.platform.drive.crypto.v1.GetBulkFileFEKResponse.results:type_name -> agio.platform.drive.crypto.v1.FileFEKResult
	0,  // 2: agio.platform.drive.crypto.v1.DriveKeyManagerService.CreateFileKey:input_type -> agio.platform.drive.crypto.v1.CreateFileKeyRequest
	2,  // 3: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetFileFEK:input_type -> agio.platform.drive.crypto.v1.GetFileFEKRequest
	5,  // 4: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetBulkFileFEK:input_type -> agio.platform.drive.crypto.v1.GetBulkFileFEKRequest
	8,  // 5: agio.platform.drive.crypto.v1.DriveKeyManagerService.FetchCompanyKEK:input_type -> agio.platform.drive.crypto.v1.FetchCompanyKEKRequest
	10, // 6: agio.platform.drive.crypto.v1.DriveKeyManagerService.ProvisionCompanyKEK:input_type -> agio.platform.drive.crypto.v1.ProvisionCompanyKEKRequest
	12, // 7: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetPermissionGeneration:input_type -> agio.platform.drive.crypto.v1.GetPermissionGenerationRequest
	14, // 8: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetSTSCredentials:input_type -> agio.platform.drive.crypto.v1.GetSTSCredentialsRequest
	16, // 9: agio.platform.drive.crypto.v1.DriveKeyManagerService.RotateFileFEK:input_type -> agio.platform.drive.crypto.v1.RotateFileFEKRequest
	18, // 10: agio.platform.drive.crypto.v1.DriveKeyManagerService.RotateCompanyKEK:input_type -> agio.platform.drive.crypto.v1.RotateCompanyKEKRequest
	1,  // 11: agio.platform.drive.crypto.v1.DriveKeyManagerService.CreateFileKey:output_type -> agio.platform.drive.crypto.v1.CreateFileKeyResponse
	3,  // 12: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetFileFEK:output_type -> agio.platform.drive.crypto.v1.GetFileFEKResponse
	7,  // 13: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetBulkFileFEK:output_type -> agio.platform.drive.crypto.v1.GetBulkFileFEKResponse
	9,  // 14: agio.platform.drive.crypto.v1.DriveKeyManagerService.FetchCompanyKEK:output_type -> agio.platform.drive.crypto.v1.FetchCompanyKEKResponse
	11, // 15: agio.platform.drive.crypto.v1.DriveKeyManagerService.ProvisionCompanyKEK:output_type -> agio.platform.drive.crypto.v1.ProvisionCompanyKEKResponse
	13, // 16: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetPermissionGeneration:output_type -> agio.platform.drive.crypto.v1.GetPermissionGenerationResponse
	15, // 17: agio.platform.drive.crypto.v1.DriveKeyManagerService.GetSTSCredentials:output_type -> agio.platform.drive.crypto.v1.GetSTSCredentialsResponse
	17, // 18: agio.platform.drive.crypto.v1.DriveKeyManagerService.RotateFileFEK:output_type -> agio.platform.drive.crypto.v1.RotateFileFEKResponse
	19, // 19: agio.platform.drive.crypto.v1.DriveKeyManagerService.RotateCompanyKEK:output_type -> agio.platform.drive.crypto.v1.RotateCompanyKEKResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_key_manager_proto_init() }
func file_key_manager_proto_init() {
	if File_key_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_manager_proto_rawDesc), len(file_key_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_manager_proto_goTypes,
		DependencyIndexes: file_key_manager_proto_depIdxs,
		MessageInfos:      file_key_manager_proto_msgTypes,
	}.Build()
	File_key_manager_proto = out.File
	file_key_manager_proto_goTypes = nil
	file_key_manager_proto_depIdxs = nil
}
