/*
 * JuiceFS, Copyright 2026 Juicedata, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package meta

import (
	"fmt"
	"syscall"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

// newRenderNode creates a direct redisMeta on the given DB (no proxy, no OIDC —
// the render-node topology of SRS §7), chroots it to subdir and wraps it with
// RenderMeta under the given Company KEK.
func newRenderNode(t *testing.T, db int, subdir string, kek []byte, kekVersion uint32, volumeUUID, companyID string) *RenderMeta {
	t.Helper()
	m, err := newRedisMeta("redis", fmt.Sprintf("%s/%d", encTestRedisAddr(), db), testConfig())
	require.NoError(t, err)
	rm := m.(*redisMeta)
	_, err = rm.Load(true)
	require.NoError(t, err)
	require.NoError(t, rm.NewSession(true))
	t.Cleanup(func() { _ = rm.Shutdown() })
	if subdir != "" {
		require.Equal(t, syscall.Errno(0), rm.Chroot(Background(), subdir))
	}
	return NewRenderMeta(rm, kek, kekVersion, volumeUUID, companyID, "companies/"+companyID)
}

// TestRenderFullCycle (AC-4, FR-RND-9): a render node (direct Redis + local KEK,
// no proxy/OIDC/PG) and a user client (via the Meta Proxy) interoperate — each
// opens files created by the other and both resolve the same plaintext FEK.
func TestRenderFullCycle(t *testing.T) {
	env := newEncryptTestEnv(t, 2, true)
	kekA := randomBytes(t, kekSize)
	env.keyMgr.mu.Lock()
	env.keyMgr.kek = kekA
	env.keyMgr.mu.Unlock()

	ctx := Background()
	user := uuid.New().String()
	cctx := userCtx(t, ctx, user)

	// The user client (proxy path) creates a file.
	var inode Ino
	var attr Attr
	require.Equal(t, syscall.Errno(0), env.client.Create(cctx, RootInode, "scene.exr", 0644, 022, 0, &inode, &attr))
	require.True(t, attr.Encrypted)

	// The render node (direct Redis, same Company KEK) opens the same file and
	// must resolve exactly the FEK the proxy path delivers.
	format := env.meta.GetFormat()
	render := newRenderNode(t, 2, "", kekA, 1, format.UUID, testCompanyID)

	var openAttr Attr
	require.Equal(t, syscall.Errno(0), env.client.Open(cctx, inode, syscall.O_RDONLY, &openAttr))
	require.Len(t, openAttr.Fek, fekSize)

	var renderAttr Attr
	require.Equal(t, syscall.Errno(0), render.Open(ctx, inode, syscall.O_RDONLY, &renderAttr))
	require.Equal(t, openAttr.Fek, renderAttr.Fek, "render node must resolve the same FEK as the user client")

	// Reverse direction: the render node creates a file locally (FEK generated
	// and wrapped under the Company KEK); the user client opens it via the proxy.
	var rinode Ino
	var rcreate Attr
	require.Equal(t, syscall.Errno(0), render.Create(ctx, RootInode, "render.exr", 0644, 022, 0, &rinode, &rcreate))
	require.True(t, rcreate.Encrypted)
	require.Len(t, rcreate.Fek, fekSize)

	// The user client discovers the file by name (the proxy populates its
	// inode→path cache on lookup, which Open requires for authz) and opens it.
	var uinode Ino
	var userAttr Attr
	require.Equal(t, syscall.Errno(0), env.client.Lookup(cctx, RootInode, "render.exr", &uinode, &userAttr, false))
	require.Equal(t, rinode, uinode)
	require.Equal(t, syscall.Errno(0), env.client.Open(cctx, uinode, syscall.O_RDONLY, &userAttr))
	require.Equal(t, rcreate.Fek, userAttr.Fek, "user client must resolve the FEK generated by the render node")
}

// TestRenderCrossCompany (FR-RND-13, FR-TEST-12): company isolation is enforced
// twice — the chroot hides other companies' trees from name-based access, and
// the cryptography fails closed with EIO if a file wrapped under another
// company's KEK is reached by direct inode anyway.
func TestRenderCrossCompany(t *testing.T) {
	env := newEncryptTestEnv(t, 3, true)
	kekA := randomBytes(t, kekSize)
	kekB := randomBytes(t, kekSize)
	env.keyMgr.mu.Lock()
	env.keyMgr.kek = kekA
	env.keyMgr.mu.Unlock()

	ctx := Background()
	user := uuid.New().String()
	cctx := userCtx(t, ctx, user)

	// Company A's tree: companies/a/secret.exr, created through the user path.
	var companiesInode, aInode, bInode Ino
	var dattr Attr
	require.Equal(t, syscall.Errno(0), env.client.Mkdir(cctx, RootInode, "companies", 0755, 022, 0, &companiesInode, &dattr))
	require.Equal(t, syscall.Errno(0), env.client.Mkdir(cctx, companiesInode, "a", 0755, 022, 0, &aInode, &dattr))
	var secretInode Ino
	var secretAttr Attr
	require.Equal(t, syscall.Errno(0), env.client.Create(cctx, aInode, "secret.exr", 0644, 022, 0, &secretInode, &secretAttr))
	require.True(t, secretAttr.Encrypted)

	// Company B's prefix must exist for its chroot.
	require.Equal(t, syscall.Errno(0), env.client.Mkdir(cctx, companiesInode, "b", 0755, 022, 0, &bInode, &dattr))

	format := env.meta.GetFormat()

	// A render node of company A (chrooted to companies/a) reads the file.
	renderA := newRenderNode(t, 3, "companies/a", kekA, 1, format.UUID, testCompanyID)
	var aAttr Attr
	require.Equal(t, syscall.Errno(0), renderA.Open(ctx, secretInode, syscall.O_RDONLY, &aAttr))
	require.Len(t, aAttr.Fek, fekSize)

	// A render node of company B (chrooted to companies/b, different KEK):
	renderB := newRenderNode(t, 3, "companies/b", kekB, 1, format.UUID, testCompanyID)

	// 1. Name-based access is blocked by the chroot.
	var bInode2 Ino
	var bAttr Attr
	require.Equal(t, syscall.ENOENT, renderB.Lookup(ctx, RootInode, "secret.exr", &bInode2, &bAttr, false))

	// 2. Direct inode access (chroot bypass) is blocked by the cryptography:
	//    EIO and no key material leaks (fail-closed).
	var bOpen Attr
	require.Equal(t, syscall.EIO, renderB.Open(ctx, secretInode, syscall.O_RDONLY, &bOpen))
	require.Nil(t, bOpen.Fek)
}
